### ISSUE TITLE
Chat / Allow charts originating in Google to be copied and pasted directly into Chat

### ISSUE THREAD

**Issue by jboniface** [Expensify/Expensify.cash#1037]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

**Platform - version:**  
All platforms, 280

**Action Performed (reproducible steps):**
1. Create a chart in Google Sheets by adding some numbers to cels then clicking Insert > Chart
2. Click on the chart
3. Copy the chart onto your clipboard
4. Go to Expensify Cash
5. Sign in then start a DM with a test account
6. Attempt to paste the chart into the text box
7. Observe that nothing is pasted

**Expected Result:**
The chart should be pasted into Expensify Cash just like an image would be, prompting the Upload modal

**Actual Result:**
The chart is not pasted

*Notes / Screenshots*
![102930343-3b79eb00-446a-11eb-9f3f-75e324c6628f](https://user-images.githubusercontent.com/24399930/102930968-76c8e980-446b-11eb-91c4-045c990c2946.png)

view the job on Upwork [here](https://www.upwork.com/jobs/~0110edc1e751673186).

**Comment by laurenreidexpensify** [comment]
Have offered to two contributors - waiting for confirming of acceptance.

**Comment by anthony-hull** [comment]
Hi I've started setting up my environment for running all the target platforms on physical devices. I'll post again once I have tested out the bug and put together a strategy.

**Comment by anthony-hull** [comment]
The code currently only handles paste events that have files.
`this.props.onPasteFile(event.clipboardData.files[0]);`
Google sheet charts are stored in the clipboard on copy as items (blobbs). 

the structure of the object is below:

```
DataTransferItemList {0: DataTransferItem, 1: DataTransferItem, 2: DataTransferItem, length: 3}
0: DataTransferItem {kind: "string", type: "text/html"}
1: DataTransferItem {kind: "string", type: "application/x-vnd.google-docs-embedded-chart-clip+wrapped"}
2: DataTransferItem {kind: "string", type: "application/x-vnd.google-spreadsheet-embedded-object+json"}
```

For this issue I propose where there is no file in the event, checking for the type: "application/x-vnd.google-docs-embedded-chart-clip+wrapped". When this is present to take the  DataTransferItem {kind: "string", type: "text/html"} blobb and render the html as an image and pass this as a file to the onPasteFile function.

Assumptions:
0: DataTransferItem {kind: "string", type: "text/html"} will render to the copied table. I haven't tested this out yet.

Improvements:
Later you might want to add support for other Mime types. I will try to implement this in a way where you can extend the handling of other types.

Observations:
I tried copy and pasting a video file and chrome pasted the file name rather than the file.
Dragging the video file brought it to the upload modal.

Currently this implementation is not async. Pasting a very large file blocks the page for a long time.

I suggest a feature be made to handle uploading async and with progress bars etc.

**Comment by quinthar** [comment]
FYI, just read about this -- not sure it is useful yet, but to put on our radar: https://www.androidpolice.com/2019/12/17/google-chrome-testing-new-raw-clipboard-access-feature-to-expand-copy-paste-functions/

**Comment by quinthar** [comment]
According to https://evercoder.github.io/clipboard-inspector/ the HTML should be a binary-encoded image.  I just tested that page using a simple chart, and it looks like the clipboard contains:

![image](https://user-images.githubusercontent.com/575186/103371897-72ad5500-4a85-11eb-9b2f-86d1681ed4bb.png)

Given that it's just a base64 encoded PNG, it might be easier to just yank it out and base64 decode -- then you have a binary PNG.  This avoids the need to basically render that HTML into an image: it just directly gets the image.

I think a better solution that avoids any generic HTML rendering step.

**Comment by anthony-hull** [comment]
That's a handy tool! thank you for the share.
I hadn't looked inside it yet :) I'm glad it's just an encoded PNG. 
Thanks, I will look at that tomorrow.

**Comment by anthony-hull** [comment]
It might make sense to unify the drop and paste handling logic as well in a later feature.

**Comment by anthony-hull** [comment]
Pasting in PR body to continue discussion here before moving to PR stage.

Added handler for when google charts MIME type is found in the paste event.
Handler converts the embedded base64 image into a Blobb to create a File object to be passed to the modal.

It is not possible to copy charts in the iOS and Android native apps. Hence I have left the below tests for iOS and Android unticked. The expected pattern for sharing a chart is using the native share functions in the OS.

I did have a short investigation on iOS simulator. When I pasted on the iOS simulator it didn't have any of the extra google specific MIME items present in the event. It only gave the text/html item, which would make detection more challenging. but I stopped this line of investigation due to the above reasons. this was only possible because I was browsing the sheets website on my dev machine and could copy the chat, when I tried to access sheets.google.com on the iPhone it pushed me to the app without option to load the web interface.

**Comment by puneetlath** [comment]
Wow, awesome! Would this solution also work for images copied from a google doc? Or would we need a separate implementation for that?

**Comment by anthony-hull** [comment]
From testing pasting a graph from sheets to docs and then copy pasting it to the app I found the graph was included as an embedded image in html with a URL to the Google user content CDNin the paste event. So without checking and assuming images from docs are the handled the same way it wouldn't take much effort detect that case and to get the image from the URL and pass it to the modal.

**Comment by anthony-hull** [comment]
> Wow, awesome! Would this solution also work for images copied from a google doc? Or would we need a separate implementation for that?

```
    checkForAttachment(event) {
        const {files, types} = event.clipboardData;
        const TEXT_HTML = 'text/html';
        const GOOGLE_MIME = {
            CHART: 'application/x-vnd.google-docs-embedded-chart-clip+wrapped',
            DOCS_IMAGE: 'application/x-vnd.google-docs-image-clip+wrapped'
        };
        if (files.length > 0) {
            // Prevent the default so we do not post the file name into the text box
            event.preventDefault();
            this.props.onPasteFile(event.clipboardData.files[0]);
        }
        if (types.includes(GOOGLE_MIME.CHART || GOOGLE_MIME.DOCS_IMAGE)) {
            event.preventDefault();
            const chartHTMLString = event.clipboardData.getData(TEXT_HTML);
            const domparser = new DOMParser();
            fetch(domparser.parseFromString(chartHTMLString, TEXT_HTML).images[0].src)
                .then(x => x.blob())
                .then(x => new File([x], pasted_image.png, {}))
                .then(this.props.onPasteFile);
        }
    }
```
With some minor tweaks it does work. Since I was already using fetch to convert to a blob, it can handle getting the image from the google CDN. However now there is a network call, some error handling around that needs to be added.

In my testing google always seemed to convert the images to .PNGs so I removed my logic to use the mime type to construct the correct file extension as it introduced a dependancy:

`.then(x => new File([x], `pasted_image.${mime.extension(x.type)}`, {}))`
This implementation could be used in an optimistic way where it always tries to parse any paste event with the text/html type if no other handler in the checkForAttachment matches. What do you think?

**Comment by stephanieelliott** [comment]
Sounds like we like the solution being proposed, @quinthar @puneetlath are we ready to approve this proposal so that @anthony-hull can move forward with the PR?

**Comment by stephanieelliott** [comment]
@anthony-hull I think you're all set here, feel free to move forward with the PR.

**Comment by anthony-hull** [comment]
thanks @stephanieelliott  I have reopened the PR. There were some outstanding questions I had. It has led me to have a fairly lengthy explanation in the PR around the different complete solutions present in the commit history.
