### ISSUE TITLE
Streamline Android notification design

### ISSUE THREAD

**Issue by quinthar** [Expensify/Expensify.cash#1098]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

**Platform - version:**  Android

**Action Performed (reproducible steps):**
1. Get two accounts A and B (eg, dbarrett@quinthar.com, and dbarrett@expensify.com)
2. Send a message from A to B
3. Observe the design of the push notification that appears on B's Android phone

**Expected Result:**
Note how it looks very streamlined on Slack:
![image](https://user-images.githubusercontent.com/575186/103114891-5a68b080-4615-11eb-97aa-99797b4bc7ff.png)

**Actual Result:**
Note how it looks very clunky on Expensify.cash:
![image](https://user-images.githubusercontent.com/575186/103114914-71a79e00-4615-11eb-8dbc-121c0760e435.png)

**Notes/Photos/Videos:** 
Please do the following:
1. Remove the extraneous "Expensify" line -- this is already shown by "Expensify.cash" on the first line
2. Move the user's name to be in front of "Expensify.cash" on the first line
3. Remove the "New message from" preamble, as that's pretty obvious
4. Remove the quotes around the message itself
5. Put the sender's profile image in the notification

**Logs - JS/Android/iOS (if applicable)**:
(n/a)

Upwork posting [here](https://www.upwork.com/jobs/~01556acaa3d714c013).

**Comment by Harshitdev** [comment]
I have picked this issue.

I will comment on the strategy for this issue shortly.

**Comment by jboniface** [comment]
@Harshitdev are you still planning to work on this? if so, please provide your proposal ASAP, or we will need to cancel and reassign to another developer

**Comment by whitesnow1120** [comment]
@jboniface  I am fixing this issue and have a problem.

**Comment by whitesnow1120** [comment]
@quinthar  @arielgreen @jboniface I tested many times but I can't see any notifications on the emulator and physical device too. I signed into two accounts (web/iOS/desktop and Android) and sent the message from the web/iOS/desktop to Android. 
It is not working on production env and dev env too.
Should I change something (i.e. permission) for my test accounts to allow the notifications?

**Comment by stephanieelliott** [comment]
Hey @whitesnow1120 can you ask this question in the #expensify-contributors Slack channel? We should be able to help you troubleshoot this there.

**Comment by whitesnow1120** [comment]
Yes. I ask this question in the #expensify-contributors Slack channel.
![Untitled](https://user-images.githubusercontent.com/59010279/104265239-cceee280-5495-11eb-8659-2adb4983ace0.jpg)

**Comment by whitesnow1120** [comment]
Hi @arielgreen I submitted the solution on upwork.

**Comment by whitesnow1120** [comment]
To solve this fix, I need to change some backend API call (sending push notifications).
I don't need to change any frontend code because push notifications can be handled in the backend, not the frontend.

- Requirements
1. Remove the extraneous "Expensify" line -- this is already shown by "Expensify.cash" on the first line
In the backend code, the title was included in the request of the sending API call.
So we can remove it.
2. Move the user's name to be in front of "Expensify.cash" on the first line
We can add the name parameter in the request of sending push notification API call.
3. Remove the "New message from" preamble, as that's pretty obvious
"New message from " + $username is added wherein the backend code. So we can remove it. ($message)
4. Remove the quotes around the message itself
The quotes were added wherein the backend code ($message). We can remove it.
5. Put the sender's profile image in the notification
Yes, we can add the icon parameter in the request of the sending push notification API call so that the user can see the sender's avatar instead of the default app icon.

Original backend code:
$request = [
   'audience' => [
       'named_user' => $stringAccountIDs,
    ],
   'notification' => [
        'alert' => $message,
        'android' => [
            'title' => 'Expensify',
            'extra' => [
                'payload' => json_encode($pushData),
                'fromExpensify' => true,
             ],
        ],
        'ios' => [
           'extra' => [
                'payload' => $pushData,
                'fromExpensify' => true,
           ],
          'sound' => 'default',
        ],
    ],
    'device_types' => [
        'android',
        'ios',
    ],
];

Changed backend code:
$request = [
    'name' => $username + ' · Expensify.cash',
    'push' => [
        'audience' => [
            'named_user' => $stringAccountIDs,
        ],
        'notification' => [
        'alert' => $message,
            'android' => [
                'extra' => [
                    'payload' => json_encode($pushData),
                    'fromExpensify' => true,
                ],
                'icon': $avatar,
            ],
            'ios' => [
                'extra' => [
                    'payload' => $pushData,
                    'fromExpensify' => true,
                ],
                'sound' => 'default',
            ],
        ],
        'device_types' => [
            'android',
            'ios',
        ],
    ]
];

**Comment by stephanieelliott** [comment]
Thanks @whitesnow1120! We're working on looking into that API update, we'll get back with you soon!

**Comment by whitesnow1120** [comment]
Thanks @stephanieelliott

**Comment by roryabraham** [comment]
Hi @whitesnow1120. We've talked about your suggestion, and come to the following conclusions:

> 1. Remove the extraneous "Expensify" line -- this is already shown by "Expensify.cash" on the first line
In the backend code, the title was included in the request of the sending API call.
So we can remove it.

Yep, we agree with this. We can replace the title field with:

- For chat reports (like all Expensify.cash reports), the name of the user who sent the message, falling back on their email or phone number
- For all other reports, the name of the report

> 2. Move the user's name to be in front of "Expensify.cash" on the first line
We can add the name parameter in the request of sending push notification API call.

Looking at the [api docs](https://docs.airship.com/api/ua/#operation-api-push-post) for UA, it looks like `name` is not valid as a top-level argument for the endpoint used to send push notifications, `POST /api/push`. So the suggestion you've posted is an invalid API request. That said, I believe the changes we landed on for (1) above would achieve the desired effect you were hoping for on Android.

> 3. Remove the "New message from" preamble, as that's pretty obvious

Yep, we agree that we can do this for Expensify.cash notifications.

> 4. Remove the quotes around the message itself
The quotes were added wherein the backend code ($message). We can remove it.

Yep, again we agree that this is a change we can make for Expensify.cash notifications

> 5. Put the sender's profile image in the notification
Yes, we can add the icon parameter in the request of the sending push notification API call so that the user can see the sender's avatar instead of the default app icon.

We like the idea here but we don't think it will work. The [api docs for the icon parameter](https://docs.airship.com/api/ua/#schema-tag-platform-overrides-icon) describe it as: “A string representing an image file included in the application’s resources.” However, all our user icons are stored in cloudfront and therefore wouldn’t be included in the application’s resources. We would need the image to be included as a URL which can be fetched by the client when the push notification is received OR for the image itself to be sent along with the push notification, perhaps in a base64 encoded format or something. Can you continue investigating a solution for this please?

**Comment by whitesnow1120** [comment]
I found another solution.
`$request = [
    'name' => $username + '· Expensify.cash',
    'push' => [
      'audience' => [
        'named_user' => $stringAccountIDs,
      ],
      'notification' => [
          'alert' => $message,
          'android' => [
              'extra' => [
                  'payload' => json_encode($pushData),
                  'fromExpensify' => true,
              ],
              'icon': $avatar,
          ],
          'ios' => [
              'extra' => [
                  'payload' => $pushData,
                  'fromExpensify' => true,
              ],
              'sound' => 'default',
          ],
      ],
      'message' => [
          'icons' => [
               'list_icon' => "http://cdn.example.com/message.png"
          ]
      ],
      'device_types' => [
          'android',
          'ios',
        ],
    ]
];`
The [api docs for the icons parameter](https://docs.airship.com/api/ua/) describe it as: "A JSON dictionary of string key and value pairs representing icons. At this time, only the list_icon key is supported. Values must be URI/URLs to icon resources. For resources hosted by UA, use the following URI format ‘ua:<resource_id>’."

**Comment by roryabraham** [comment]
We're going to close this an revisit internally.
