### ISSUE TITLE
Signing in with `exitTo` doesn't work

### ISSUE THREAD

**Issue by quinthar** [Expensify/Expensify.cash#1118]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

**Platform - version:**
Desktop web (all?)

**Action Performed (reproducible steps):**
1. Sign in as normal
2. Navigate to a report
3. Click "Sign out"
4. Note that there is an `exitTo` in the URL
5. Enter an email address to sign in
6. Note that it hangs there forever

**Expected Result:**
Expected to see password/2FC page

**Actual Result:**
Hung with a spinner forever

**Notes/Photos/Videos:** 
![image](https://user-images.githubusercontent.com/575186/103263677-68903700-495d-11eb-9b3d-65bdf7644f12.png)
 
**Logs - JS/Android/iOS (if applicable)**:

**Comment by quinthar** [comment]
FYI, when it's hung, it just keeps throwing this error into the console every second:

![image](https://user-images.githubusercontent.com/575186/103302191-e84aef80-49b7-11eb-866d-209cfa361416.png)

**Comment by quinthar** [comment]
interestingly, when I attempt to reproduce this inside an incognito window, it doesn't happen.  Accordingly, it must be something about my unique Onyx state that is causing this.  So for this issue, can you please develop a theory for what Onyx state might have caused this issue to happen, and then "harden" the code in such a fashion such that whatever it is, it doesn't break in the future?  After all, I'm supposed to be signed out here -- all my state should have been cleared.  Something:

1. Didn't clear my Onyx correctly, and
2. Isn't handling my broken Onyx state in a "defensive" manner (ie, gracefully ignoring the problem)

**Comment by quinthar** [comment]
Here is the state of my localStorage; something in there is causing this to break on signin.

![image](https://user-images.githubusercontent.com/575186/103302775-4a582480-49b9-11eb-8008-622c69ecb86b.png)

**Comment by quinthar** [comment]
Ah shit, now it's not happening.  Well, I don't know how to reproduce this one anymore.  So I think this issue should be diagnosing that uncaught exception, and gracefully handling it in the future such that it doesn't happen again.

**Comment by quinthar** [comment]
Maybe it's still borked.  Here was the localstorage state while I tried to sign in, and this time it let me through the first page:

![image](https://user-images.githubusercontent.com/575186/103303062-eb46df80-49b9-11eb-9a8e-55b54deea00e.png)

And here it is after I got through the email entry box, and now it broke at the password page:

![image](https://user-images.githubusercontent.com/575186/103303050-e71ac200-49b9-11eb-927c-0ee7b8618232.png)

Once again it's an infinite loop doing this error every second:

![image](https://user-images.githubusercontent.com/575186/103303101-00bc0980-49ba-11eb-8921-fae1c3125d5d.png)

Maybe it has nothing to do with localStorage, and is instead something weird in the DOM?

**Comment by johnmlee101** [comment]
reproduced 
![image](https://user-images.githubusercontent.com/5258036/103303689-9c5a7380-49d4-11eb-962e-a75a3c8941d1.png)

**Comment by arielgreen** [comment]
Reproduced, confirmed incognito mode works as expected.

Posted on [Upwork](https://www.upwork.com/jobs/~01ee1ce262e64c6023).

**Comment by basaksilasanli** [comment]
I going to be taking it on this issue

**Comment by TheRohitSharma** [comment]
May or may not be related, but it definitely hangs for me if I switch tabs and then come back to the password input and attempt to log in.

**Comment by r8** [comment]
I was able to reproduce it only with switching tab and coming back to the sign in tab.
I'm not sure if others, who reproduced it, switched the tab in the process, but this flow has 100% reproducibility.

There was a post in the Slack about new steps for contributors:

> 5. **Hired contributors post their solution proposals directly on the GitHub issue**
> 6. Expensify reviews and provides feedback on proposal on GH issue
> 7. Contributors move forward with creating PRs

Even though I'm itching to write the pull request, I'll post the solution first.

## Steps to reproduce

1. Login to the web app
2. Navigate to any chat
3. Click "Sign Out"
4. Switch to other tab in the browser
5. Switch back to the Sign In page
6. Wait for 3 seconds (_I know, right?_)
7. Enter the email, press "Continue"
8. Confirm that sign in hangs and doesn't continue

## The root cause

This is a combination of two issues.

When `ReportActionsView` is mounted, it adds an event listener for the app visibility change (remember the tab switching?)

```javascript
    componentDidMount() {
        this.visibilityChangeEvent = AppState.addEventListener('change', () => {
            if (this.props.isActiveReport && Visibility.isVisible()) {
                this.timers.push(setTimeout(this.recordMaxAction, 3000));
            }
        });
```

So on each app visibility change, the function `recordMaxAction` will be called, and it will send the request to the server to update last read action id.

And when `ReportActionsView` is unmounting, it should remove this listener:

```javascript
    componentWillUnmount() {
        if (this.visibilityChangeEvent) {
            this.visibilityChangeEvent.remove();
        }
```

The problem is `AppState.addEventListener` doesn't really return anything, so `this.visibilityChangeEvent` is undefined after subscription to the event. It means that `componentWillUnmount` doesn't remove the listener.

The listener is **still active** after the sign out.

![visibilityChangeUndefined](https://user-images.githubusercontent.com/130532/103469588-653ae800-4d6f-11eb-97e3-a99030db6b09.png)

When user switches to other tab and returns back to the sign in, the event triggers. After 3 seconds timeout, it send the request. But user is signed out, so server responds with 407 code. API request function calls `handleExpiredAuthToken` to try to relogin user.

```javascript
function handleExpiredAuthToken(originalResponse, originalCommand, originalParameters, originalType) {
    // Prevent any more requests from being processed while authentication happens
    Network.pauseRequestQueue();
    isAuthenticating = true;

    Authenticate({
        useExpensifyLogin: false,
        partnerName: CONFIG.EXPENSIFY.PARTNER_NAME,
        partnerPassword: CONFIG.EXPENSIFY.PARTNER_PASSWORD,
        partnerUserID: credentials.autoGeneratedLogin,
        partnerUserSecret: credentials.autoGeneratedPassword,
    })
```

This is the place where other issue happens. `handleExpiredAuthToken` pauses the network queue and tries to call `Authenticate` request, using saved credentials. But user is signed out. So `credentials` object is null. So accessing `credentials.autoGeneratedLogin` and `credentials.autoGeneratedPassword` throws an exception, which is not caught. 

So `handleExpiredAuthToken` ends prematurely. But before it tried to send the request, it paused the Network Queue. And after the exception **the queue is still on pause**.

Now user enters the email and presses "Continue" button. 

`fetchAccountDetails` request is added to the queue, but queue is on pause, so request will never be sent and "Continue" button forever hangs in loading state.

https://user-images.githubusercontent.com/130532/103470075-10e73680-4d76-11eb-8578-94283f4d5c95.mp4

## The fix

The fix should include:

1. The null check for `credentials` object, or something like this:

```javascript
    const authCredentials = credentials || {};

    Authenticate({
        useExpensifyLogin: false,
        partnerName: CONFIG.EXPENSIFY.PARTNER_NAME,
        partnerPassword: CONFIG.EXPENSIFY.PARTNER_PASSWORD,
        partnerUserID: authCredentials.autoGeneratedLogin,
        partnerUserSecret: authCredentials.autoGeneratedPassword,
    })
```

2. Proper event listener removal in `ReportActionsView`:

```javascript
    // Should have .bind(this) in constructor
    onVisibilityChange() {
        if (this.props.isActiveReport && Visibility.isVisible()) {
            this.timers.push(setTimeout(this.recordMaxAction, 3000));
        }
    }

    componentDidMount() {
        AppState.addEventListener('change', this.onVisibilityChange);
    }

    componentWillUnmount() {
        AppState.removeEventListener('change', this.onVisibilityChange);
    }
```

## Prevention of future issues

I'm not sure about it yet. 

1. I could put the request in `handleExpiredAuthToken` to `try-catch` block, but we already have the catch for the promise. So this approach would require some duplication of the catch code, because promise rejection will not be caught by `try-catch`.

2. I could wrap the whole function content with `Promise.try(() => { ... });` and add the only one parent `catch`, which would handle both promise rejections and params errors. That would be cleaner, but looks a bit weird to me.

3. The cleanest way would be `async/await` with `try/catch`, but you don't use it anywhere in your code. So that probably makes the №2 approach the winner.

**Comment by ajimpa** [comment]
I was able to reproduce the issue.
I will take this issue to fix.

**Steps to reproduce**
1. Login to the web app
2. Click "Sign Out"
3. Switch to other tab in the browser
4. Switch back to the Sign In page
5. Wait for 3 seconds (I know, right?)
- There is an error msg in the developer console.
6. Enter the email, press "Continue"
7. Sign in hangs and doesn't continue

**Comment by driley8601** [comment]
I was able to reproduce issue.
**Steps to reproduce.**
1. Login
2. Click sign out
3. switch to another tab.
4. come back to sign in page.
5. after 3 second, there is a error message in dev console.
6. After that, everything is broken ( sign in doesn't work - spinning forever)

**Comment by ajimpa** [comment]
As we clicked sign out button, there is no need to automatically login ( this is not expired token case )
We need to add exception handler in handleExpiredAuthToken function.
```
function handleExpiredAuthToken(originalResponse, originalCommand, originalParameters, originalType) {
    if(!credentials) return;
    // Prevent any more requests from being processed while authentication happens
    Network.pauseRequestQueue();
    isAuthenticating = true;

    Authenticate({
        useExpensifyLogin: false,
        partnerName: CONFIG.EXPENSIFY.PARTNER_NAME,
        partnerPassword: CONFIG.EXPENSIFY.PARTNER_PASSWORD,
        partnerUserID: credentials.autoGeneratedLogin,
        partnerUserSecret: credentials.autoGeneratedPassword,
    })
```

**Comment by r8** [comment]
Hey @arielgreen 
It's been a while, and we already have 1 pull request and several comments about solutions.
Maybe it's time to call for reviewers?

**Comment by arielgreen** [comment]
@r8 good to proceed with your PR, thanks!

**Comment by marcaaron** [comment]
>The fix should include: The null check for credentials object

@r8 what do you think about preventing the call to `Authenticate()` entirely if we no longer have `credentials`? I'm thinking perhaps we should not be calling `handleExpiredAuthToken()` at all in this case since:

- We know it will fail.
- Requests that happen after sign out should ideally not be re-queued or run at all.

We should still want to keep track of when a request fires after credentials have been cleared (after sign out) so we can track down the root cause as you've done here. So maybe in this case we can not retry the request at all and log something so we know to look into it (most likely someone will have forgotten to clean up an event listener)?

**Comment by marcaaron** [comment]
@ajimpa That solution alone will not solve this issue since it doesn't address the underlying cause of this particular bug (which is that we have a network request firing after we have logged out).
