### ISSUE TITLE
[Consumer UI Refresh] Create a Floating Action Button component by adding a fixed position icon

### ISSUE THREAD

**Issue by marcaaron** [Expensify/Expensify.cash#1224]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

- Using the resource provided add a fixed position touchable icon component called `FAB.js` in `/components`
- The FAB must always be the same distance from the RIGHT EDGE of the _sidebar area_ regardless of screen width
- We are not yet using this element so it should remain hidden for now but easily testable (use a prop `isHidden` for now).
- It must use a `Pressable` and take an `onPress` callback
- It must also accept a prop of `isActive` and display an alternate view when this prop is `true`
- When moving from the not active to active state the SVG can be rotated via a transform and the fill color set to gray
- No external dependencies are allowed
- Here is the exact location where it should sit at both wide screen views and small screen widths and the two states of the FAB shown

![FAB example](https://user-images.githubusercontent.com/32969087/104237380-0d9a1d80-53fc-11eb-8200-e0894c28b51b.png)

**Asset:**
[plus.svg.zip](https://github.com/Expensify/Expensify.cash/files/5799401/plus.svg.zip)

**Upwork:**
https://www.upwork.com/jobs/~0134b44cccd50f0085

**Comment by lucas-neuhaus-dev** [comment]
Hello,

Proposal for the solution:

- Import the plus.svg file on assets/images;
- Create a class-based component src/components/Expenseicons/PlusIcon.js. The component is class-based so I can use it in _Animated.createAnimatedComponent(PlusIcon)_  to animate the fill color. I will need to call **// eslint-disable-next-line react/prefer-stateless-function** to create it;
- Create a new style in src/styles/styles.js called sidebarFab;
- Create a new component src/components/FAB.js, that takes onPress, isActive, and isHidden props. It renders an _Animated.createAnimatedComponent(Pressable)_ with the _Aniamted.createAnimatedComponent(PlusIcon)_ inside.
- Create the isFabActive and isFabHidden state props and declare the toggleFab() on HomePage.js and pass it down ( -> SidebarView -> FAB ).


I am defining the state and the function in the HomePage because everything else seems to be handled this way.

**Comment by marcaaron** [comment]
>Create a class-based component src/components/Expenseicons/PlusIcon.js. The component is class-based so I can use it in Animated.createAnimatedComponent(PlusIcon) to animate the fill color

Is it possible to use a `ref` with `Animated.Value` instead for this? I'm not sure if one would be better than the other. But curious whether it would be possible? I think that might be my first approach and then run two animated values in parallel for the fill color and transform.

>Create a new style in src/styles/styles.js called sidebarFab;

This style be named `floatingActionButton` since we may use it in other places besides the sidebar

>Create a new component src/components/FAB.js, that takes onPress, isActive, and isHidden props. It renders an Animated.createAnimatedComponent(Pressable) with the Aniamted.createAnimatedComponent(PlusIcon) inside.

Does the `Pressable` need to be animated? Maybe only the orientation of the SVG and fill color should be animated? But let me know if I'm missing something.

>I am defining the state and the function in the HomePage because everything else seems to be handled this way.

👍  yep the FAB should just change based on props only and not have state of it's own.

Everything else looks good.

**Comment by lucas-neuhaus-dev** [comment]
> Is it possible to use a ref with Animated.Value instead for this? I'm not sure if one would be better than the other. But curious whether it would be possible? I think that might be my first approach and then run two animated values in parallel for the fill color and transform.

The thing is, only animatable components can be animated. I am still using `ref` with `Animated.Value` to control the animation. Because the Icon component needs to be animatable, I need to call the function I mentioned earlier (createAnimatedComponent), and it doesn't work with functional components (throws an error).

I am going to show some code below to exemplify the solution.

> This style be named floatingActionButton since we may use it in other places besides the sidebar

Ok. It might make sense to separate the positioning styling (`position`, `bottom` and `right`) somewhere else then, what do you think?

> Does the Pressable need to be animated? Maybe only the orientation of the SVG and fill color should be animated? But let me know if I'm missing something.

We have three properties to animate: `backgroundColor`, `rotate`, and (the icon's) `fill`. I am really missing a way to animate them all with just one animatable component. So I was thinking of animating the `backgroundColor` and `rotate` in the Pressable, and the `fill` in the Icon (so the Icon component is cleaner).

**FAB.js**
```
...
import {PlusIcon} from './Expensicons';

const AnimatedPressable = Animated.createAnimatedComponent(Pressable);
const AnimatedIcon = Animated.createAnimatedComponent(PlusIcon);

const FAB = ({onPress, isActive, isHidden}) => {
    const animatedValue = useRef(new Animated.Value(0)).current;
    const rotate = animatedValue.interpolate({
        inputRange: [0, 1],
        outputRange: ['0deg', '225deg'],
    });
    const backgroundColor = animatedValue.interpolate({
        inputRange: [0, 1],
        outputRange: [colors.green, colors.gray3],
    });
    const fill = animatedValue.interpolate({
        inputRange: [0, 1],
        outputRange: [colors.white, colors.black],
    });

    return (
        <AnimatedPressable
            onPress={toggleFab}
            style={[styles.floatingActionButton, {transform: [{rotate}], backgroundColor, , display: isHidden ? 'none' : 'flex'}]}
        >
            <AnimatedIcon fill={fill} />
        </AnimatedPressable>
    );
};
...
```

**PlusIcon.js**
```
...
// eslint-disable-next-line react/prefer-stateless-function
class PlusIcon extends React.Component {
    render() {
        return (
            <PlusSvg                
                height={this.props.height}
                width={this.props.width}
                fill={this.props.fill}
            />
        );
    }
}
...
```

**Comment by marcaaron** [comment]
>The thing is, only animatable components can be animated. I am still using ref with Animated.Value to control the animation. Because the Icon component needs to be animatable, I need to call the function I mentioned earlier (createAnimatedComponent), and it doesn't work with functional components (throws an error).

Ok Cool. Just checking as I did not understand this!

>It might make sense to separate the positioning styling (position, bottom and right) somewhere else then, what do you think?

It's OK to hardcode these values for now. We can improve it when we need to in the future.

>We have three properties to animate: backgroundColor, rotate, and (the icon's) fill. I am really missing a way to animate them all with just one animatable component.

Ok, looking at the asset it's really just a plus and no circle and what is being asked I now understand what you mean.

Everything looks good to me!

One more note, we are not yet using the React hooks so if you can find another way and use a class component that would work best. Let me know if it's OK?

**Comment by marcaaron** [comment]
We can chat more in the reviews when you are ready with the PR. Thanks!

**Comment by lucas-neuhaus-dev** [comment]
PR created.
https://github.com/Expensify/Expensify.cash/pull/1233
