### ISSUE TITLE
Inconsistencies Between Animation Speeds Amongst Various Platforms

### ISSUE THREAD

**Issue by yuwenmemon** [Expensify/Expensify.cash#1358]
**Platform - version:**  All (Cross platform) - version 1.0.1-389

**Action Performed (reproducible steps):**
1. Click the Profile Image icon at the top of the sidebar on the left.
1. A settings modal should animate in on the right.
1. Close the settings modal
1. Observe the differences in animation time across platforms.

**Expected Result:** The animation should behave the same across all platforms.

**Actual Result:**
On iOS, the transition is smooth (300ms in and out as expected):
![105801273-a62cb380-5f4d-11eb-98e2-3146fddbd890](https://user-images.githubusercontent.com/4741899/106180965-da70c180-6151-11eb-8c9b-33241f162af9.gif)

However, on Web, the out transition is virtually indetectable:
![Kapture 2021-01-28 at 10 18 11](https://user-images.githubusercontent.com/4741899/106181258-3a676800-6152-11eb-8f03-2502b2488f61.gif)

Inconsistencies of a similar nature exist between iOS/Android as well.

**Notes/Photos/Videos:** Added above
 
**Logs - JS/Android/iOS (if applicable)**: N/A

**Comment by yuwenmemon** [comment]
Added to Upwork https://www.upwork.com/jobs/~01655ae22d1440c25f

**Comment by parasharrajat** [comment]
Hey @yuwenmemon. I have found the cause of inconsistency between web browsers and android device animations. In fact, I have some solution ready to be criticized. I would like to work on this.

Thanks.

**Comment by parasharrajat** [comment]
So the issue is due to the animation happening with the full width of the screen so in mobile it's fine as the modal takes the full width of the screen but on desktop, the modal has a width equal to the sidebar but the animation is running on the full width of the window.

So for the laptop, it would be 1366px. This causes a little pause before the modal is slide-in from the right as it has to travel `1366 - width of sidebar` to the left to be visible. this is delay is detectable if we increase the animation time. This also has an issue as we are using the Easing function ease thus when you close the modal as the modal will be hidden quickly due to it only takes the width of the sidebar to hide it in the right direction but the animation will run for complete screen width which would be 1366px so the modal will be hidden quickly but the animation is still running which also blocks the other part of the screen. To see this we can set the animation time to 3 sec and observe the behavior.

So by default, the `SlideIn` animation distance is `100px` but the `React-native-modal` is overriding it to the width of the screen which is the whole issue.
To solve this we can override the animation definition and pass it over our own where we calculate the distance the width of the sidebar. Thus it will behave the same for all the devices and screens.

below animations are running on 3000 secs to know the difference.

| Before | After |
|-----------|--------|
| ![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/24370807/106278956-a1c00d80-6261-11eb-99c2-5e511339b5ca.gif) | ![ezgif com-video-to-gif](https://user-images.githubusercontent.com/24370807/106278975-b0a6c000-6261-11eb-89c4-181046a69c9d.gif) |

**Comment by marcaaron** [comment]
This solution sounds good to me. 🚀
