### ISSUE TITLE
Add hover feedback to chat rows found in Left Hand Navigation

### ISSUE THREAD

**Issue by laurenreidexpensify** [Expensify/Expensify.cash#1439]
Problem:
The LHN on web & desktop does not have any mouse hover feedback, and thus users don’t have a clear idea of which element they are interacting with. It also makes the product feel a bit lifeless and stagnant.

Solution:
Implement a simple background color change on hover for chat rows found in the LHN. The background color for hover should use the color themeColors.componentBG which will look like this:

![105834416-bafb5c80-5fca-11eb-97ac-322adcd0f3b0](https://user-images.githubusercontent.com/62073721/107356493-c8374180-6ac8-11eb-9155-cd0316ad72ec.png)

There should be no hover styles added to an active chat row (the first chat row in the screenshot above)

**Comment by parasharrajat** [comment]
Hey @laurenreidexpensify. Seems a quick work. let me help with this one.

## Proposal
1. Show the hover feedback on the Web using the backgroundColor from the theme.
2. Show the feedback on the Mobile app using TouchableOpacity which should show touch feedback (if not already).
3. Exclude the hover effect on active Rows.

**Comment by parasharrajat** [comment]
I just come to know we already have this functionality as a `Hoverable` component so I will use that component to show the feedback.

**Comment by parasharrajat** [comment]
Few Questions:
1. Should this hover effect be visible on the Search view, group chat list, new chat list?

**Comment by laurenreidexpensify** [comment]
Hi @parasharrajat is there a reason why you have opened a PR for this already? I haven't sent an offer to you on Upwork for this as per the standard process for picking up our issues. Can you please hold off on doing any work on this unless we move forward with offering a contract for this in Upwork. Thank you.

**Comment by parasharrajat** [comment]
Sure. I thought I have to create the above functionality so I started early but I found the component so It finished early. No issues, I will rollback. An I will follow this pattern next time.

**Comment by laurenreidexpensify** [comment]
@shawnborton if you have a moment can you review this solution? Thanks

**Comment by roryabraham** [comment]
@laurenreidexpensify [This proposal](https://github.com/Expensify/Expensify.cash/issues/1439#issuecomment-775892355) seems out-of-date, since we already have a [Hoverable](https://github.com/Expensify/Expensify.cash/tree/master/src/components/Hoverable) component in Expensify.cash.

Also, the solution references CSS, and just to be clear we use plain Javascript objects and React Native style props, not actual CSS.

**Comment by parasharrajat** [comment]
@roryabraham  I realized that we already have `Hoverable` component so I mentioned that in my next comment. By CSS I meant the style prop itself.
## Updated Proposal
 1. As we already have Hoverable Functionality so We just need to use the `Hoverable Component` to wrap over rows in LHN.
 2. Now based on the `hovered` prop on the child function, we can update the style of the underlying `View` where we check if the Option is active then add nothing otherwise add the Hover effect here.
  https://github.com/Expensify/Expensify.cash/blob/449171b9db5407556e959937a4eb5928af96a0bd/src/pages/home/sidebar/OptionRow.js#L79

Question: 
1. Should this hover effect be visible on the Search view, group chat list, new chat list?

**Comment by roryabraham** [comment]
> Should this hover effect be visible on the Search view, group chat list, new chat list?

Yes, all of the above, feel free to submit the PR. Also note that you should add some color constants to the default theme in `src/styles/themes/default` like `hoverComponentBG: colors.gray1` and `activeComponentBG: colors.gray2` and reference those in your styles.

**Comment by parasharrajat** [comment]
Ok. Thanks. I don't would be needing to add a new variable as the one we need is already there. But I can update the PR as per the feedback.

**Comment by parasharrajat** [comment]
@shawnborton BackgroundColor of NewChat and NewGroup Page is `#fff`. So what should be the hover effect for these pages.
![image](https://user-images.githubusercontent.com/24370807/107680107-727ab900-6cc3-11eb-8de2-1a62bc8341d6.png)

**Comment by shawnborton** [comment]
I think those should use `gray1` as a hover color. 

Thinking through this some more... we have `componentBG: colors.white`, so maybe it makes sense to have `componentBGHover: colors.gray1` - this should work for all of the items in the rightDocked modal where we have a white background. 

Then since we have `sidebar: colors.gray1` maybe it makes sense to have `sidebarHover: colors.white` - this would be the hover color for anything found in the home screen/left hand navigation. 

How does that sound?

**Comment by roryabraham** [comment]
@parasharrajat Not sure if you misunderstood my last comment, but all our colors in Expensify.cash come from [here](https://github.com/Expensify/Expensify.cash/blob/97ab9fe2e0ac0c9b2cfc14b433ce1f45426d348b/src/styles/themes/default.js). Please update this file to add two new fields:

```
hoverComponentBG: colors.gray1,
activeComponentBG: colors.gray2
```

**Comment by parasharrajat** [comment]
I like it. Let's do it this way.

**Comment by parasharrajat** [comment]
We need to update the `OptionRow` Component to be able to change styles in different locations. I am wondering what would be a good way to do it. 
1. Pass a style prop `hoverStyle`. OR
2. Use `getOptionStyles.js` file and take the styles from there. For this as well, we need to pass a prop for identifying the placement.

**Comment by roryabraham** [comment]
I would go with (1), just pass a `hoverStyle` style prop
