### ISSUE TITLE
Update :hover/:focus/:outline border color for text inputs

### ISSUE THREAD

**Issue by sakluger** [Expensify/Expensify.cash#1458]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

Upwork Job: https://www.upwork.com/jobs/~01db974a75a3feab77

**Platform - version:**
Desktop, Web

**Action Performed (reproducible steps):**
When focusing into a form field on either the homepage or Search, the outline color for the text fields vary in color and border width, which doesn't look coherent with the Expensify.cash design system.

**Expected Result:**
We'd like to make it so we have full control over the :hover/:focus/:outline styles for these text inputs that we can control and use across all Expensify.cash platforms.

**Actual Result:**
Desktop sign-in screen:
![image](https://user-images.githubusercontent.com/5997400/107676083-9a2f3a00-6c4d-11eb-9207-fc5df95b0f4f.png)

Desktop Left-Hand-Nav search:
![image](https://user-images.githubusercontent.com/5997400/107676142-aadfb000-6c4d-11eb-9dd2-91f1fc1fe50f.png)

Web Left-Hand-Nav search:
![image](https://user-images.githubusercontent.com/5997400/107676181-b337eb00-6c4d-11eb-863d-2a59d211bfe7.png)

**Comment by tugbadogan** [comment]
Hi @sakluger,

I'd like to work on this issue if it's still available.

### Proposal

I found a function called `addOutlineWidth` and I can use it for removing outline from text inputs on web and desktop platforms. On search input, we're using `textInputReversed` for `styleFocusIn` prop of `TextInputWithFocusStyles`. 
https://github.com/Expensify/Expensify.cash/blob/eaba9026a62fcfe355591af578f41e533496af0e/src/styles/addOutlineWidth/index.js#L13-L18

I'm planning to wrap `textInputReversedFocus` style with `addOutlineWidth` function to remove the outline.
https://github.com/Expensify/Expensify.cash/blob/58bfd3dd4c03f04fd30b931e8ab3735296f1249c/src/styles/styles.js#L252

And I'll replace all `TextInput` with `TextInputWithFocusStyles`.  For example, login form input can be fixed by changing this TextInput with TextInputWithFocusStyles.
https://github.com/Expensify/Expensify.cash/blob/257518b71ebd9687e733bcc777e0f07a10fd61c3/src/pages/signin/LoginForm/LoginFormNarrow.js#L68

**Comment by tugbadogan** [comment]
Hi @sakluger, is this issue still relevant? Are you looking for another way of solving this issue?

**Comment by shawnborton** [comment]
I believe we will be changing what our inputs look like soon, so I think we should close this one out for now as the work done here would be for a short-lived benefit. That being said @tugbadogan look out for a new contributor issue soon regarding new inputs.
