### ISSUE TITLE
Setting password via /setpassword signs in user. Does not generate re-authentication credentials.

### ISSUE THREAD

**Issue by jboniface** [Expensify/Expensify.cash#1482]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

view the job on Upwork [here](https://www.upwork.com/jobs/~01ccfce466ee66ebaf).

**Platform - version:**  
Current

# Problem
It doesn't seem like we are generating re-authentication credentials when a user hits `https://expensify.cash/setpassword/[validateCode]`.

# Why is this important?
I think anyone setting a password will be logged out when their authToken expires. And ideally they won't be logged out at all once a password is set.

# Solution
Generalize the logic [here](https://github.com/Expensify/ReactNativeChat/blob/5739dc888092440ebfc1463fe47db6e7159f90b8/src/libs/actions/Session.js#L127-L165) into a private action that can be used in the `signIn()` and `setPassword()` flows.

**Comment by anthony-hull** [comment]
For this issue I would refactor the functionality into a new function in the Session.js action file and call that from within the signIn and setPassword functions, making it re-usable and keeping the code DRY. This is to all setPassword to set up the re-authentication credentials for when the token expires without reproducing the code from the signIn action.

I would first try to re-produce the "authToken expiration after re-setting" edge case.
I would then call then confirm the desired refreshing of auth tokens take place after the change.

How long lived are the tokens? Do you have any advice on how to re-produce this edge case on demand?
Otherwise I would look at a way to force this to happen to speed the feedback loop up if the token lives longer than a few minutes.

**Comment by marcaaron** [comment]
Plan sounds good. We can reproduce an `authToken` expiring by modifying the `localStorage` key `session` and deleting some characters from `session.authToken` - tapping on a new chat or trying to take any API action should in this case not log you out but refresh the token instead. 


https://user-images.githubusercontent.com/32969087/108240312-d13e9900-70ee-11eb-8125-abd62723111d.mp4

**Comment by anthony-hull** [comment]
I'm having trouble using the setPassword flow here:
http://localhost:8080/#/setpassword/
I requested a reset link from expensify.com and took the token from the end of the URL I was emailed by concierge. The first time I used it I set the password to my current password. It then send me back to the login page and also my console showed around 10s to 100s of get calls with app version numbers in the response made in a few seconds. 

Now when I try the same pathway it just hangs on the set password button. do you have any suggestions I can e2e test the set password flow?

**Comment by marcaaron** [comment]
>my console showed around 10s to 100s of get calls with app version numbers in the response made in a few seconds

Are you able to share a screen shot of this?

**Comment by anthony-hull** [comment]
Apologies no. I'll try to reproduce it tomorrow. I'm signing off for the
night.

**Comment by anthony-hull** [comment]
I wasn't able to reproduce this today. I was able to complete the change password flow however. I think it was because I had cleared the local storage and so didn't have an email set which is required for the setPassword to work as the reset page doesn't ask the user to enter one for the form.

> I think anyone setting a password will be logged out when their authToken expires 

When I force the expiry error from the API by corrupting the token as marcaaron suggested, The user is left 'logged in' and not sent to the login page. @jboniface is this the preferred behaviour?

**Comment by marcaaron** [comment]
>The user is left 'logged in' and not sent to the login page

Can you confirm what actions you took + provide screenshots of your `localStorage` `credentials` key?

**Comment by anthony-hull** [comment]
> > The user is left 'logged in' and not sent to the login page
> 
> Can you confirm what actions you took + provide screenshots of your `localStorage` `credentials` key?

the content of the key is: `{"password":"*******"}`
![image](https://user-images.githubusercontent.com/47184118/108543765-699a7080-72dd-11eb-8906-0072ef77de8c.png)

The * represents the password I entered in the set password box.

The steps are:
Trigger password reset on expensify.com for your account.


1. Make sure you are logged out.
2. Navigate to: http://expensify.cash/#/setpassword/[code from magic link in email here]
3. Make sure you have credentials.login key set to your email address in local storage. (or hardcode your email in line 226 in Session.js)
4. Set a new password.
5. Edit the session.authtoken in local storage and deface it somehow.
6. if you have any photos in the chat log, they will disappear. And you can't do any API actions. But you are not set to the login page.

**Comment by marcaaron** [comment]
Are you looking at JS console logs... do you see that there is a failing attempt to reauthenticate or any kind of error? This might be due to a recent change we made, but doesn't change the scope of this issue - which is to make sure the user's session remains authenticated.

>if you have any photos in the chat log, they will disappear. And you can't do any API actions.

Right, this should not happen

**Comment by anthony-hull** [comment]
The console just spouted this:
react_devtools_backend.js:2430 Could not get betas 
{jsonCode: 407, title: "Session expired", message: "Your session has expired. Please sign in again.", requestID: "085d2825d600004083f68cf000000001"}
jsonCode: 407
message: "Your session has expired. Please sign in again."
requestID: "085d2825d600004083f68cf000000001"
title: "Session expired"

Also in the network tab I have many of these:
```
Request URL: http://localhost:8080/api?command=Get
Request Method: POST
Response:

{"jsonCode":407,"title":"Session expired","message":"Your session has expired. Please sign in again.","codeRevision":"bceda6ca22e881b0fd854b8ba899172c88753b48","requestID":"085d2b7d2b00002d28bb8d9000000001"}
```

**Comment by marcaaron** [comment]
yep, we should not see that. After calling `setPassword()` the user should be able to re-authenticate.

**Comment by anthony-hull** [comment]
Apologies I'm multitasking. I didn't answer your question.
I can't see any attempts to authenticate

**Comment by marcaaron** [comment]
you'd have to step through the code with a debugger to see this process happen :)

**Comment by anthony-hull** [comment]
> yep, we should not see that. After calling `setPassword()` the user should be able to re-authenticate.

Now it reauthenticates with my PR so this shouldn't happen anymore. 

Should I open an issue for not being redirected to login if there isn't any credentials to reauthenticate with?

**Comment by marcaaron** [comment]
>Should I open an issue for not being redirected to login if there isn't any credentials to reauthenticate with?

I think this is a scenario that should theoretically never happen so it's not a real issue unless we are experiencing some negative effects from it.

**Comment by anthony-hull** [comment]
ok great. That was my original question, apologies if I confused the
matter.
thanks for your input :)
