### ISSUE TITLE
[IOU] Add isAppInstalled logic to Expensify.cash

### ISSUE THREAD

**Issue by jboniface** [Expensify/Expensify.cash#1526]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

view the post on Upwork [here](https://www.upwork.com/jobs/~0152f89613f3e316fe).

**Platform - version:**  
current

We require a method of detecting installed apps for the Expensify.cash app on Android & iOS.

1. Install and implement the [react-native-check-app-install](https://github.com/redpandatronicsuk/react-native-check-app-install) package. 
2. Create a helper function under libs `isAppInstalled()` (similar to [getPlatform](https://github.com/Expensify/Expensify.cash/tree/master/src/libs/getPlatform)) which takes two params: `iosScheme, androidPackageId`, and returns true if the selected app is installed.
3. Within the helper function, `getPlatform()` should be used to determine which library function to use: 
    -  **Android:** `AppInstalledChecker.isAppInstalledAndroid(androidPackageId)`
    - **iOS:** `AppInstalledChecker.checkURLScheme(iosScheme)`
4. As this is only used on mobile, this should be build within an `index.native.js` file (unfortunately the params are different for iOS/Android, so we cant create `index.android.js|`index.ios.js``). Also, the default `index.js` function should always return false.

**Comment by Maftalion** [comment]
Hello, I'd like to take on this task. 

The technical explanation is pretty straightforward above so I'll be following those steps and making sure the platforms are set up correctly. it looks like there might be issues with this package though so i'll be sure to test it out and confirm it's working: https://github.com/redpandatronicsuk/react-native-check-app-install/issues/23

**Question**
- `checkURLScheme` seems to be supported on both platforms, do you still need the platform specific logic to use `isAppInstalledAndroid` as well?

**Comment by SameeraMadushan** [comment]
Hi,
I submitted a proposal on Upwork regarding this issue.

The provided deliverables are pretty much clear and I'm sure can do the task.

Since you have used `"react-native": "0.63.3"` this library needs some fix with auto-linking. I can fix that issue with `react-native.config.js `

This library does support only a few apps for both platforms. (https://github.com/redpandatronicsuk/react-native-check-app-install/blob/master/app-list.js)
So, as you mentioned we will have to go with `isAppInstalledAndroid ` and `checkURLScheme `

- If your URLSchemes are same for the both Android and iOS, then we don't need this library. Because internally it uses react native `Linking.canOpenURL()` to check the app's existence.

**Comment by aliabbasmalik8** [comment]
We can do this JOB with Deep Linking [](https://reactnative.dev/docs/linking) I tested it on IOS and it's worked for me.
Here is the source code

created helper function `isAppInstalled`  in `libs` folder

![image](https://user-images.githubusercontent.com/31027036/108617473-9306e980-740e-11eb-88b3-7d2606109bbd.png)
 
 Add an array of `LSApplicationQueriesSchemes` in info.plist
 
![image](https://user-images.githubusercontent.com/31027036/108617532-06a8f680-740f-11eb-810d-6a4bd14d16bd.png)

did some configuration `AppDelegation.m`

![image](https://user-images.githubusercontent.com/31027036/108617553-3c4ddf80-740f-11eb-9aa9-51e631eb85c3.png)

**Comment by karvik09** [comment]
Hi,
I would be interested for this task Please find below my approach.

We can include the more application support by creating our own AppList rather than [Available App List](https://github.com/redpandatronicsuk/react-native-check-app-install/blob/master/app-list.js) in [react-native-check-app-install](https://github.com/redpandatronicsuk/react-native-check-app-install) for those which are not supported in package.
![Screenshot from 2021-02-23 13-42-35](https://user-images.githubusercontent.com/22873270/108818217-1119ea80-75df-11eb-8496-6f22ba99fdbe.png)

Then after we can use utility functions to check Either the app is already installed or not Like this in `index.native.js` & return false for `index.js`.
![Screenshot from 2021-02-23 13-42-05](https://user-images.githubusercontent.com/22873270/108818727-cf3d7400-75df-11eb-92b9-63f7a2271f6e.png)

**Comment by Julesssss** [comment]
Thanks for all of your proposals and comments! @Maftalion I'm going to pass this issue onto the second responder as you were hired for #1508.

@SameeraMadushan, would you like to move forward with the implementation? Thanks for your suggestion about reusing `checkURLScheme` for Android, we should also be able to use a single `native.js` file for both Android & iOS.

**Comment by SameeraMadushan** [comment]
> Thanks for all of your proposals and comments! @Maftalion I'm going to pass this issue onto the second responder as you were hired for #1508.
> 
> @SameeraMadushan, would you like to move forward with the implementation? Thanks for your suggestion about reusing `checkURLScheme` for Android, we should also be able to use a single `native.js` file for both Android & iOS.

Thank you @Julesssss 
I accept the offer. We can handle it inside `native.js`.
I will work on this 👍🏻

**Comment by Julesssss** [comment]
@SameeraMadushan 

Replying to questions from the UpWork issue: 

> 1) Can we use URL schemes for both Android and iOS?
> 2) If Yes, as I mentioned In the proposal, we can use Linking.canOpenUrl() to check app existence. So still do I need to go with react-native-check-app-install library?

Great point. Our goal for now is simply to be able to detect if we can route the user into the Venmo app successfully prior to attempting to do this. It looks like `Linking.canOpenUrl()` would be preferable, so yeah no need to use the 3rd party library for now, as long as it works correctly with the Venmo app (the schema is `venmo://`).

One note is that as we're outside of the US this can be a bit tricky to test (I had to use a VPN in order to get Venmo installed on my personal devices).

Also, would you mind confirming that you've read the instructions in the latest UpWork messages? This will give you some additional info regarding testing and getting access to our Slack channel for support.

**Comment by SameeraMadushan** [comment]
@Julesssss  Awesome!

Yes, I've read the instructions and sent you a message.

**Comment by Julesssss** [comment]
PR has been merged.
