### ISSUE TITLE
Pressing Enter key does not always submit forms on sign in screen

### ISSUE THREAD

**Issue by NicMendonca** [Expensify/Expensify.cash#1549]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

**Platform - version:**  desktop 

**Action Performed (reproducible steps):**

1. Sign out and refresh Expensify.cash
2. Enter email and press return
3. Enter password and press return
4. Verify you get signed in
5. Sign out but do not refresh
6. Enter email and press return
7. Observe that the form is not submitted

**Expected Result:**
Hitting return should consistently submit the sign in form (really any form)

**Actual Result:**
Not _consistently_ submitting

**Notes/Photos/Videos:** 
 
**Logs - JS/Android/iOS (if applicable)**:

Job:  https://www.upwork.com/jobs/~01394d3648bb7249b5

**Comment by soloarevalo** [comment]
Hi
Here is my solution.
When the Enter ASCII code is catched, I'll submit the form.

I can definitely fix your issue.
Let's discuss via chat.

Best

**Comment by aliabbasmalik8** [comment]
`onSubmitEditing` have some issue we can handle this scenario with `onKeyPress` Here is working solution
removed `onSubmitEditing` event and add `onKeyPress` event.

```
onKeyPress(event) {
        if (event.nativeEvent.key === 'Enter') {
            this.validateAndSubmitForm();
        }
    }

```

![image](https://user-images.githubusercontent.com/31027036/108938647-6211f900-7648-11eb-8f75-baf50db80b4d.png)

**Comment by soloarevalo** [comment]
Hello.
I can definitely fix your issue.
When can we start to work?

Thank you

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by SameeraMadushan** [comment]
Hi @NicMendonca 

Here is my proposal. I have submitted a proposal on Upwork as well.

### Problem
Hitting return consistently not submitting the forms.
I checked the mentioned scenarios and these are my findings.
These are the scenarios that this bug shows up.
- Login forms (Both narrow and wide views)
- Password form
- Github username form
- Set password page

### Solution
To handle this I will have to capture `onKeyPress` event in `TextInput`

But the problem is if I replace `onSubmitEditing` with `onKeyPress`, Then it will not work on mobile.
So my solution is,

- I will create a helper function in src/libs (eg: `formSubmitHandler`)
- Inside the `formSubmitHandler` folder, there will be two files `index.native.js` and `index.js`
- `index.js` implementation will check for `Enter` key press.
- `index.native.js` implementation will just return `false`.
- Then I will use `formSubmitHandler` function with `onKeyPress`

#### Implementation
index.js
![image](https://user-images.githubusercontent.com/18027269/109045895-25063f00-76fa-11eb-865c-b42b6ed57246.png)

index.native.js
![image](https://user-images.githubusercontent.com/18027269/109046036-4ff09300-76fa-11eb-99f8-8e4ba6829c7d.png)

Handling the function
![image](https://user-images.githubusercontent.com/18027269/109046220-80d0c800-76fa-11eb-84c9-0a614d72f55d.png)

Defining a new function to avoid inline function
![image](https://user-images.githubusercontent.com/18027269/109046347-a3fb7780-76fa-11eb-970b-aacb16e2656b.png)

After implementing this, mobile will follow `onSumbitEditing` and web, desktop, and mobile web will follow `onKeyPress`
I have tested this and it's working with no regression 💯 

Thanks,
Sameera

**Comment by marcaaron** [comment]
@SameeraMadushan thanks for this proposal. Rather than a helper method I'd suggest we create a component that wraps the `TextInput` and adds this behavior. Something like a cross platform version of this that accepts all props of `TextInput` but calls `this.props.onSubmit()` when either `onSubmitEditing` or `onKeyPress` is triggered the two cases ...

```jsx
<TextInputWithSubmit 
    onSubmit={() => doMyThing()}
/>
```

This way we can just replace the `TextInput` with `TextInputWithSubmit` and not have to implement the helper method for every `TextInput`. Thoughts?

Also, I am curious to know why is it that `onSubmitEditing` only triggers _once_? This seems unexpected behavior and like a bug with `react-native` or `react-native-web`. Rather than do this work-around first I'd suggest we at least try to explain why it works inconsistently or open an issue in the main repo with a reproduction. Maybe there is some obvious reason why [this code](https://github.com/necolas/react-native-web/blob/d037506200548d51dc523637732a71a30cfd7cff/packages/react-native-web/src/exports/TextInput/index.js#L246-L277) doesn't work?

**Comment by aliabbasmalik8** [comment]
@marcaaron 

on the web after submitting the form `event.isDefaultPrevented()` is become true so that's the reason check failed in [this code](https://github.com/necolas/react-native-web/blob/d037506200548d51dc523637732a71a30cfd7cff/packages/react-native-web/src/exports/TextInput/index.js#L246-L277)

In React we used `event.preventDefault()` while submitting form. the benefit is in this way page not reloaded and after calling this `event.preventDefault()`, `event.isDefaultPrevented` will become true.

Reference: https://www.robinwieruch.de/react-preventdefault

**Comment by marcaaron** [comment]
Interesting, so I'm not sure that makes sense then and must be a bug. I added a debugger and saw that `event.isDefaultPrevented()` is true. But why?

>the benefit is in this way page not reloaded and after calling

I'm not sure what you mean as this `input` does not exist in a `form`. 

![Screen Shot 2021-02-25 at 10 26 25 AM](https://user-images.githubusercontent.com/32969087/109212921-1e0c1a80-7754-11eb-9578-cb38c315bc86.png)

At what point does the event get prevented?

**Comment by marcaaron** [comment]
I think maybe it's here -> https://github.com/Expensify/Expensify.cash/blob/38b392173a5e990a0d0e5fe9b327a14f7ae722ad/src/libs/KeyboardShortcut/index.js#L50

**Comment by marcaaron** [comment]
Probably we are not unbinding the `Enter` key properly in `BaseModal`

**Comment by SameeraMadushan** [comment]
@marcaaron Yes, you are correct.
It happens because of that `event.preventDefault(); ` in keyboardshortcut/index.js

after removing the `event.preventDefault()` it works as expected.

When the user logs in addEventListner will start, and when the user logs out event listener won't get removed.
It will get remove and add again only when the page is refreshed.

**Comment by aliabbasmalik8** [comment]
@marcaaron 

In `BaseModal` we have an issue while `unsubscribe`  `KeyboardShortcut` .
We can fix this by adding `componentWillUnmount` lifecycle and `unsubscribe` `KeyboardShortcut`  there.
Updated and working code

![image](https://user-images.githubusercontent.com/31027036/109216046-ec26a280-77ab-11eb-916c-859d3c3c242c.png)

**Comment by SameeraMadushan** [comment]
The problem is in BaseModal subscribe and unsubscribe happens without a lifecycle method.
It uses `onModalShow` and `onModalHide` to subscribe and unsubscribe.

Solution:
We will have to,

- remove `subscribe` from `onModalShow`
- remove `unsubscribe` from `onModalHide`
- add useEffect to subscribe and unsubscribe

```
useEffect(() => {
      KeyboardShortcut.subscribe('Escape', props.onClose, [], true);
      KeyboardShortcut.subscribe('Enter', props.onSubmit, [], true);

      return () => {
          KeyboardShortcut.unsubscribe('Escape');
          KeyboardShortcut.unsubscribe('Enter');
      };
  }, []);
```

Then this will work as expected.

**Comment by marcaaron** [comment]
Thanks for the solutions. @aliabbasmalik8 is closer since we should not subscribe in `componentDidMount()` or `useEffect()`  otherwise many similar event handlers would be set. So we will also need to convert `BaseModal` into a class component and use the `componentWillUnmount` lifecycle method. `useEffect` should not be used as we are avoiding hooks for now.
