### ISSUE TITLE
Make desktop hot reload use a different port than web

### ISSUE THREAD

**Issue by laurenreidexpensify** [Expensify/Expensify.cash#1571]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

**Problem**
We recently introduced a hotreload feature for the desktop platform. It works with webpack, and is hard-coded to listen on localhost:8080.

In most cases that works fine, but let's say you have some feature that's somehow different on web vs desktop, and you are trying to test that feature by running web and desktop at the same time. If you first run npm run web, it will do a web-specific webpack build, and host that with the webpack dev server on localhost:8080. Then, you run npm run desktop, and it will do a desktop-specific webpack build, and host that with the webpack dev server on localhost:8081. I think webpack does this automatically – if you specify port 8080 but it's already occupied, it will just use port 8081. But the electron client will be connected to localhost:8080 regardless, and thus will be using the web-specific code.

**Why is this important?**
This happened to @marcaaron while he was testing something, and it's confusing to figure out without the context of how the desktop hot reload feature works.

**Solution**
Make desktop's hot reload feature listen on a different port dynamically if the webpack build ends up using a different port that 8080.

**Comment by parasharrajat** [comment]
Hello Guys, I would to work on this feature as I have setup the Hot-reload for Desktop.
#### Terms
1. WDS - Webpack-dev-server.
1. Frontend - react app built with WDS

### Problem
1. We need WDS for building the Frontend of the app and then we have to use the exposed endpoint in the electron window to Enable the Hot-reload.
2. Now as the issue say the port could be busy with some another process and WDS will start the Fronted on some port dynamically which electron will not be able to know about.
3. Due to WDS does not expose the PORT on the environment variables, its not possible for the electron process to know the port in easy way.
4. Both the processes are separate.

### Proposed Solution 1
1. We can use the `onListening` hook to get the port of WDS and then store it into a file in the root of source tree.
```
   devServer: {
        onListening(server) {
            const port = server.listeningApp.address().port;
            console.debug('Listening on port:', port);
            ... write the port to a temp file 
            // such as .cache/wds
        },
    },
```
4. Now in the electron process we can watch on the file path `.cache/wds`.
5. Now as soon as the port is available on the path `.cache/wds`.
```
WEBPACK_DEV_SERVER_PORT=80xx
```
we load the URL into the electron main window and stop the file watcher.
6. We can start both process in parallel using npm scripts.

### Proposed Solution 2
1. we create a start script in the desktop folder.
2. This file will start and control both the processes for Frontend and Electron(main) just by spawning then with the correct argument as passed in the npm scripts.
3. We use https://www.npmjs.com/package/portfinder to find a available port and then pass it to the WDS process and we use the same in the main process using the Environment variable.

Please ask for clarification if needed, I have come to know that I am not good with explaining things in first go.

**Comment by marcaaron** [comment]
The `portfinder` solution seems pretty simple to me and also means we will not have to create a temporary file? Since it's only a dev dependency and some modifications to the start script. Any thoughts @roryabraham ?

**Comment by roryabraham** [comment]
Yeah, I agree solution 2 seems better.

**Comment by laurenreidexpensify** [comment]
Sounds like we're good to go ahead with Solution 2 here Rajat 👍🏽
