### ISSUE TITLE
Create a JS utility to generate a GitHub comparison URL

### ISSUE THREAD

**Issue by arielgreen** [Expensify/Expensify.cash#1577]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

# Problem
As part of our new Expensify.cash Deploy & QA process, we'll need an easy way to view differences between versions. To do so, we'll generate links to a [GitHub comparison](https://docs.github.com/en/github/committing-changes-to-your-project/comparing-commits).

# Why is this important?
This will be an important step for engineers to be able to view changes introduced by a release and track regressions.

# Solution
Create a Javascript utility function in [expensify-common](https://github.com/Expensify/expensify-common) called `generateVersionComparisonURL` that takes in:

1) A `repoSlug`
2) A `tag` (version number)
3) A `semverLevel` that's one of `['MAJOR', 'MINOR', 'PATCH', 'BUILD']

And then:

1) [Fetch the tags of the repo](https://octokit.github.io/rest.js/v18#repos-list-tags)
2) Search through the results to find the tag of the previous version of the appropriate `semverLevel`.
3) Return a URL formatted like: `https://github.com/Expensify/Expensify.cash/compare/<previous_version_tag>...<current_version_tag>`

**Note:** If it doesn't already exist, this function should be stored in a class called `GithubUtils` that takes in an authenticated `octokit` client as a parameter to its constructor. This function will be used from the context of Github Actions,  where we'll always have an authenticated client available.

## To be considered complete

- Document testing
- Provide automated unit tests.

[Internal issue](https://github.com/Expensify/Expensify/issues/155334)
[Upwork listing](https://www.upwork.com/jobs/~019d7eda14a41e4569)

**Comment by SombreroElGringo** [comment]
Hello,

I will proceed like this to resolve this problem:

- I will create a new method `generateVersionComparisonURL` In the class `GithubUtils`. This function will have the following parameters:
- - `repoSlug` the slug of the repository 
- - `tag` the tag we want to compare with  
`semverLevel `
 - - `semverLevel` will determine with which tag we should compare. Possible value are MAJOR, MINOR, PATCH and BUILD 

- Then we should fetch the list of tags from the repo via `listTags`

- Following the parameter `semverLevel` we should select the good tag to compare and return the url. For select the good tag we can slip or use a regex to get the different `semverLevel` values received from the API

Examples:
Let’s say we have the following tags
2.2.2, 2.2.1, 2.2.0, 2.1.0, 2.0.0, 1.1.0 and 1.0.0

- `generateVersionComparisonURL(“my-repo”, “2.2.2”, “MAJOR”)` should return `https://github.com/Expensify/Expensify.cash/compare/1.0.0...2.2.2`

- `generateVersionComparisonURL(“my-repo”, “2.2.2”, “MINOR”)` should return `https://github.com/Expensify/Expensify.cash/compare/2.1.0...2.2.2`

- `generateVersionComparisonURL(“my-repo”, “2.2.2”, “PATCH”)` should return `https://github.com/Expensify/Expensify.cash/compare/2.2.1...2.2.2`

- `generateVersionComparisonURL(“my-repo”, “2.2.2”, “BUILD”)` should return `https://github.com/Expensify/Expensify.cash/compare/2.2.1...2.2.2`

**Comment by arielgreen** [comment]
@SombreroElGringo, have you applied to the Upwork job as well?

**Comment by SombreroElGringo** [comment]
@arielgreen yes I applied the Upwork job as well. Name is Marc P.

**Comment by FredericoGauz** [comment]
Hi,

I will create a new class (since I could not find a GithubUtils in expensify-common) with the method generateVersionComparisonURL requested and also (already created) helper methods to make this function slim and easy to test.

I am currently directly querying the data via Postman and manually tweaking it to have a greater range of version numbers but later can adapt to use 'octokit'.

This is an working example for a comparison with the version "v2.3.1-0" for all levels:

[
  [
    'MAJOR',
    'https://github.com/Expensify/Expensify.cash/compare/v2.3.1-0...1.6.4-23'
  ],
  [
    'MINOR',
    'https://github.com/Expensify/Expensify.cash/compare/v2.3.1-0...2.3.1-1'
  ],
  [
    'PATCH',
    'https://github.com/Expensify/Expensify.cash/compare/v2.3.1-0...2.3.0-0'
  ],
  [
    'BUILD',
    'https://github.com/Expensify/Expensify.cash/compare/v2.3.1-0...v2.3.0-0'
  ]
]

I already applied in Upwork, let me know if I should proceed.

Thanks,

**Comment by roryabraham** [comment]
@SombreroElGringo Your proposal [here](https://github.com/Expensify/Expensify.cash/issues/1577#issuecomment-787040997) looks good. Just a few comments:

> For select the good tag we should slip or use a regex to get the good semverLevel values from the tags received from the API.

You should use the [semver library](https://github.com/npm/node-semver#readme) to accomplish this instead of writing your own regexes.

Also, your examples aren't exactly correct. It should provide a comparison between the highest version of the previous level. Let's say we have the following tags:
2.2.2-1, 2.2.2, 2.2.1, 2.2.0, 2.1.0-2, 2.1.0-1, 2.1.0, 2.1.2, 2.0.0, 1.1.0 and 1.0.0

> `generateVersionComparisonURL(“my-repo”, “2.2.2”, “MAJOR”)` should return `https://github.com/Expensify/Expensify.cash/compare/1.1.0...2.2.2` _not_ `1.0.0...2.2.2`

> `generateVersionComparisonURL(“my-repo”, “2.2.2”, “MINOR”)` should return `https://github.com/Expensify/Expensify.cash/compare/2.1.2...2.2.2` _not_ `2.1.0`

> `generateVersionComparisonURL(“my-repo”, “2.2.2”, “PATCH”)` should return `https://github.com/Expensify/Expensify.cash/compare/2.2.1...2.2.2`

> `generateVersionComparisonURL(“my-repo”, “2.2.2-1”, “BUILD”)` should return `https://github.com/Expensify/Expensify.cash/compare/2.2.2...2.2.2-1` _not_ `2.1.0-2...2.2.2-1`

It's a bit hard to describe with words, but it should provide a comparison between the version passed as a parameter, and the _highest version_ of the previous `SEMVER_LEVEL` version.

In the case of `BUILD`, it will always be a comparison with the previous `PATCH` version. Does that make sense?

**Comment by roryabraham** [comment]
Whatever the case, a very comprehensive set of automated tests will be the key to success here 👍

**Comment by SombreroElGringo** [comment]
@roryabraham thank you for the clarification.

Ok I will use the package `semver` for get the `comparison between the version passed as a parameter, and the highest version of the previous SEMVER_LEVEL version`.

Yeah, sure a good range of tests is mandatory for this test.

**Comment by arielgreen** [comment]
@SombreroElGringo I just sent over the offer via Upwork.

**Comment by roryabraham** [comment]
PR was missing the proper keyword to close this issue on merge. Manually closing...
