### ISSUE TITLE
[Improvement] Have the return key send a message on iPad

### ISSUE THREAD

**Issue by kadiealexander** [Expensify/Expensify.cash#1594]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

Hi team! We are looking to make an improvement to the app on iPad (but not iPhones) where the keyboard will send a message when the enter/return key is pressed, and enter a linebreak when using Shift+Enter.

**Platform - version:**  iOS - Specifically iPad **only.**

**Action Performed (reproducible steps):**

1. Log into Expensify.cash on the iPad
2. Compose a message to another user
3. Use the **Enter/Return** key on the Apple keyboard to send the message

**Expected Result:**

The message will send, and Shift+Enter creates a line break.

**Actual Result:**

The message does not send, and a line break is inserted when hitting Enter.

**Comment by kadiealexander** [comment]
Upwork post: https://www.upwork.com/jobs/~01d004351c8cf67b28

**Comment by AliYar-Khan** [comment]
We just need to set two properties for TextInput component ant those are multi line and blur on submit. After that we have to pass the onKeyPress function which will be a native Event call. That will send the message. This solution should work on both iOS and Android.

TextInputChanges will be 

-  <TextInput
                value={message}
                onChangeText={this.onMessageInputChange}
                onKeyPress={this.onKeyPress}
                returnKeyType="send"
                blurOnSubmit={false}
                multiline={false}
            />

And use the onKeyPress props only for sending a message.

- onKeyPress({ nativeEvent: { key: keyValue } }) {
    if (keyValue === "Enter") this.sendMessage();
 }

with 

- onMessageInputChange(message) {
    this.setState({
        message,
    });
}

**Comment by SameeraMadushan** [comment]
Hi,
Did some research on this and found,
In react native there's no way to capture `shift` button event.
So in that case,
If we want to submit on return key press we can have,

```
blurOnSubmit={false}
onSubmitEditing={this.submitForm}
returnKeyType="send"
```

props only for iPad. (we can check iPad with `Platform.isPad` on iOS) [https://reactnative.dev/docs/platform#ispad-ios](https://reactnative.dev/docs/platform#ispad-ios)

Cons: iPad won't be able to submit multiline messages.

No need to capture enter key events otherwise it will affect Android and iPhones.
-----
Also found in the `ReportActionCompose` constructor, there are two statements with `this.submitForm = this.submitForm.bind(this);`
Not a bug. but good to be removed.

**Comment by sadez** [comment]
Hi,

Submitting input with Enter key can be easily done with `e.nativeEvent.key === 'Enter'` and something like that in `ReportActionCompose.js`
![image](https://user-images.githubusercontent.com/8754816/109726154-7c048c00-7bb2-11eb-8277-6c7f3f7218dd.png)

We can also add a condition to verify if it's an iPad with `Platform`, but the difficulty is to handle the Shift+Enter to create new line, since onKeyPress of TextInput doesn't detect the event of shift.
Solution is to either sur some component that do keyboard event handling  like [this one](https://github.com/kevinejohn/react-native-keyevent)  or create a native bridge to do that (can be complicated)

**Comment by marcaaron** [comment]
@AliYar-Khan @SameeraMadushan doesn't seem like either of these solutions will fix the issue as they will break the ability to leave multi-line comments.

@sadez I'm not sure if this library is suitable. It looks like for iOS we can only handle `keyUp` event so how can we ever tell that the `shift` key is down? Seems like the options would be to: 

1. Find another package (if possible)
2. Submit a PR to implement the necessary change in the package shared by @sadez 
3. Do the native bridge 

Maybe reconsider if we should do this issue right now... cc @deetergp to get some more thoughts on how valuable this would be and whether it is still worth the effort (and possibly could take quite a bit of effort).

**Comment by kadiealexander** [comment]
Hi everyone! Thank you for taking the time to submit a proposal for this issue. We've spoken internally and decided to deprioritise this feature for now. 

Please take a look at our [job list](https://www.upwork.com/ab/jobs-home/8577561/all-postings) for other projects we have available!
