### ISSUE TITLE
Chat avatar does not update on historical messages

### ISSUE THREAD

**Issue by arielgreen** [Expensify/Expensify.cash#1614]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

**Platform - version**:
Desktop - Version 1.0.1-463 (1.0.1-463)
**Action Performed (reproducible steps)**:
User changed avatar image > sent chat. To reproduce this, we can have someone change their avatar > send a chat and see if the existing message lines have the new avatar.
**Expected Result**:
When someone changes their avatar, it should be reflected on all lines - new and existing messages.
**Actual Result**:
See below:

Notes/Photos/Videos: 
![image](https://user-images.githubusercontent.com/37308300/109862646-af84fc00-7c2e-11eb-8865-1342b91b6481.png)

https://github.com/Expensify/Expensify/issues/155256
https://www.upwork.com/jobs/~0134cd18cfaf0d96bf

**Comment by Oleksiy-Titarenko** [comment]
I just sent the application on upwork. please allocate this issue to me

**Comment by Oleksiy-Titarenko** [comment]
I will solve this issue perfectly.

**Comment by arielgreen** [comment]
@Oleksiy-Titarenko Per the instructions, please post your proposal for fixing the issue here.

**Comment by Oleksiy-Titarenko** [comment]
thanks. let's chat on upwork

**Comment by Oleksiy-Titarenko** [comment]
maybe image can load from the redux. then you should update the image information in the redux after updating.
Another issue can cache issue. anyway I can know the correct reason after checking the code.

**Comment by hassaantahir** [comment]
This is an architectural issue on the front-end side. There should be a single component i.e., TextMessage, which should load a profile picture from a single source (coming from the backend and stored in redux store) every time when a text message renders on the screen. So when you'll change your profile picture, at the time of API call immediately change your profile picture on the redux store as well. Then, your profile picture of all messages will instantly change at the spot.
I think there is a bug in the flow :)

**Comment by andbilous** [comment]
Hello !
My suggestions to resolve issue :
 - debug SidebarScreen, Settings page and AvatarWithIndicator component where items are fetched
 - possible server fix
 This issue is related to refetching.
Other details can be resolved with communication with your team.

**Comment by anthony-hull** [comment]
When you update your avatar, only the latest report action gets the new avatar URL. When you look at the actions in localStorage you can see the old avatar URLs against the previous actions for the active report. When you update a URL in this object directly in the local storage it updates in the chat. When an action such as a comment is created and sent by the user after changing their avatar, the correct avatar URL is added. This is because the personal details are kept up to date via the onyx subscription here:
https://github.com/Expensify/Expensify.cash/blob/78709ed6b79ed26abe21daf737f1aaaed730f32a/src/libs/actions/Report.js#L47-L51
This issue is the new value is only used to make the new action. The others are not updated.
If you refresh the page, the actions are put into the props and localStorage anew by Onyx and all the messages show with the new Avatar.

After adding a report, this function is called:
https://github.com/Expensify/Expensify.cash/blob/78709ed6b79ed26abe21daf737f1aaaed730f32a/src/libs/actions/Report.js#L245-L256
If I compared the avatar property of myPersonalDetails to that of the second newest action by the logged in user I could see the avatar has changed. If this were true I would then call:
https://github.com/Expensify/Expensify.cash/blob/78709ed6b79ed26abe21daf737f1aaaed730f32a/src/libs/actions/Report.js#L504-L520
to get all the actions and refresh the local storage with the reports with the new Avatars

**Comment by anthony-hull** [comment]
Actually I have a better idea of subscribing to the MY_PERSONAL_DETAILS via ONYX via something like this:
`
Onyx.connect({
    key: ONYXKEYS.MY_PERSONAL_DETAILS,
    callback: myUpdateReportActionsFunction,
});
`

**Comment by anthony-hull** [comment]
Actually it looks like the PERSONAL_DETAILS is not being kept up to date by ONYX. So that callback doesn't get fired after sending a new report action. 
I would dig around more in the logic of how that report gets the new avatar. I suspect it's because when it send the action to the server, the app gets that report back from pusher and replaces this optimistically added report. 
In that logic of the report being added back I could do a comparison to see if it's different like explained above. And then re-trigger a re-fetch of personal details and also reports and their actions.

I don't have any more time to do more digging today 👍

**Comment by roryabraham** [comment]
@anthony-hull Your proposal looks good. I think you would just need to update this [setAvatar](https://github.com/Expensify/Expensify.cash/blob/dbb3ad0878a3dd66a25d40fd50fc1fd70968dad1/src/libs/actions/PersonalDetails.js#L220) function to optimistically update the `MY_PERSONAL_DETAILS` Onyx key. Then you would be able to do what you suggested earlier:

`Onyx.connect({ key: ONYXKEYS.MY_PERSONAL_DETAILS, callback: myUpdateReportActionsFunction, });`

**Comment by marcaaron** [comment]
Just gonna chime in here that I think that the correct way to do this will require a refactor of how we are displaying these actions. Here are a few thoughts:

1. We need to **stop** using the `reportAction.avatar` data to show the participant avatar and instead refer only to the avatar in `personalDetails`. Probably we should also only do this when the `reportAction` is `automatic: false` (all of them are at the moment, but this will not always be the case)
2. We have no way to publish updates about the personal details in real time (e.g. tell a client that someone has updated these details) so we would need to update the personal details (or just the avatar) whenever a new comment is handled by a participant
3. We should also update the display name while we are doing this - since the exact same problem exists with it

Personally, I think this is kind of a hacky solution still since we should be sending changes about the personal details when they are updated and not when we get a message from a user. But this might be a good starting point.

**Comment by anthony-hull** [comment]
> Just gonna chime in here that I think that the correct way to do this will require a refactor of how we are displaying these actions. Here are a few thoughts:
> 
> 1. We need to **stop** using the `reportAction.avatar` data to show the participant avatar and instead refer only to the avatar in `personalDetails`. Probably we should also only do this when the `reportAction` is `automatic: false` (all of them are at the moment, but this will not always be the case)


I would agree refactoring to use personalDetails to display the avatar would be best. It did cross my mind while looking into this. It would be nice if there was a pusher subscription for personal details for this as you say below.

> 2. We have no way to publish updates about the personal details in real time (e.g. tell a client that someone has updated these details) so we would need to update the personal details (or just the avatar) whenever a new comment is handled by a participant
> 3. We should also update the display name while we are doing this - since the exact same problem exists with it
> 
> Personally, I think this is kind of a hacky solution still since we should be sending changes about the personal details when they are updated and not when we get a message from a user. But this might be a good starting point.

Agreed. if we start abstracting these details out with this issue, once the push service supports this data we can easily trigger updates to the ONXY key subscribers.


I'd like to clarify then what we should refactor to use personalDetails or (similar for the other actors) for this issue. I propose at first only refactor for the logged in user. I think it would be a good idea to have a similar approach towards other actors in reports where changes in their details can be reacted to separately from refreshing all the reports. Possibly in another issue?
There are more places this would be impacting such as the new chat side bar, search etc.

Places the current user's Avatar or name appears:

- side bar links  - _subscribes to personalDetails_
- settings page - _subscribes to personalDetails_
- above the chat view - _comes from active report (would also need refactoring to use personalDetails)_
- reportActionsView - _comes from active report (would also need refactoring to use personalDetails)_

**Comment by anthony-hull** [comment]
> Probably we should also only do this when the `reportAction` is `automatic: false` (all of them are at the moment, but this will not always be the case)

Can you please clarify what you mean by this?

**Comment by marcaaron** [comment]
>what we should refactor to use personalDetails or (similar for the other actors) for this issue. I propose at first only refactor for the logged in user. I think it would be a good idea to have a similar approach towards other actors in reports where changes in their details can be reacted to separately from refreshing all the reports. Possibly in another issue?

Hmm sorry, I'm not following why we should only make this change for the currently logged in user. There only way to react to changes in personal details is to detect those changes when a new comment is handled via Pusher. So, I might be missing what you are suggesting exactly or how/why we should even make that distinction.

>Can you please clarify what you mean by this?

Yes! So, comments are just one type of "reportAction" and although we don't support other types besides `ADDCOMMENT` (in this application) we _will_ in the future. So, we should avoid any code that makes all report action rows generically reference the `personalDetails` based on something like the `actorEmail` since in the case of an `automatic: true` action we are not always showing the user's own avatar based on the `actorEmail` and would want to fallback to the one provided by the report action.

**Comment by arielgreen** [comment]
@marcaaron can you provide an update for how Anthony should proceed?

**Comment by arielgreen** [comment]
Closing per internal discussion.
