### ISSUE TITLE
[GH Actions] Create the getReleasePullRequestList Action

### ISSUE THREAD

**Issue by arielgreen** [Expensify/Expensify.cash#1663]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

# Problem
When a production deploy completes, we need a way to gather all the PRs for that release. That way, we can comment in each that it's been deployed to production.

# Why is this important?
We need a clear audit trail of which PRs are deployed to production. To do that, we first need to know which PRs are being deployed.

# Solution
Create a Github Action called `getReleasePullRequestList` that takes a `TAG` as input and:

1. [Fetch all the Expensify.cash releases](https://octokit.github.io/rest.js/v18#repos-list-releases).
2. Filter the results to find the release prior to the one with the tag matching the input tag.
3. Execute the [`getPullRequestsMergedBetween`](https://github.com/Expensify/expensify-common/blob/58ed3e9e813a9bc1cf0dd4626ce90ef35110369c/lib/GitUtils.jsx#L13-L20) function with the tag found in step 2 and the tag passed as input.
4. Return the result of step 3.

**Apply to this posting on Upwork**: https://www.upwork.com/jobs/~0147f10a003e2162e8

https://github.com/Expensify/Expensify/issues/155144

**Comment by tugbadogan** [comment]
Hi @arielgreen

I would like to work on this issue. Here is my proposal:

- I'm planning to create `getReleasePullRequestList` function that will take a `TAG` parameter in `GithubUtils` class.
- I will fetch all the Expensify.cash releases via octokit's `listReleases` function.
- I will find the release prior to the one with the tag matching the input tag from the previous step.
- I will call `getPullRequestsMergedBetween` with input tag and prior release tag.
- I will finally return the pull request list as a `Promise`.
- I will test his function manually from a sample Github Action by passing hard-coded tag.

**Comment by arielgreen** [comment]
cc @roryabraham

**Comment by roryabraham** [comment]
@tugbadogan Looks pretty good, but I think you had a slight misunderstanding of the task:

> I will test his function manually from a sample Github Action by passing hard-coded tag.

In this issue, the deliverable actually _is_ a Github Action, similar to [these ones](https://github.com/Expensify/Expensify.cash/tree/master/.github/actions). So you should:

1) Create an action metadata file for a new Github Action similar to [this one](https://github.com/Expensify/Expensify.cash/blob/master/.github/actions/bumpVersion/action.yml)
2) Create a Node.js script that _is_ the action. So you shouldn't need to add anything to `GithubUtils`, but instead just have the Node.js script perform the steps you outlined above for the `getReleasePullRequestList` function.

A few tips:

- You'll be able to test this action by creating a custom workflow in another repo (or your fork of Expensify.cash), and executing the action as a step in that workflow.
- You can use the `@actions/core` module to access the inputs defined in the actions metadata file and to emit outputs from the action.
- You can use `@actions/github` module to get an authenticated `octokit` client.
- **Important:** Because of the way Github Actions work, we need to pre-compile the JS for our Github Actions (aka the Node.js) script using a software called `ncc`. You can do that by adding your script to the list [here](https://github.com/Expensify/Expensify.cash/blob/master/.github/scripts/buildActions.sh#L13) and running `npm run gh-actions-build`.
    - _However, if you have a windows computer,_ you'll need to run that compilation in a Linux machine of some sort (probably want to use Ubuntu). We had another contributor create a cloud instance to do that, but I would recommend using Docker to create an ubuntu VM locally on your computer, and run the compilation from in there.
    - If you have a mac or linux computer, no need to worry about this.

Does all this make sense? We have a pretty quick timeline we're shooting for on this project so I'd like this done ASAP.

**Comment by tugbadogan** [comment]
> In this issue, the deliverable actually _is_ a Github Action, similar to [these ones](https://github.com/Expensify/Expensify.cash/tree/master/.github/actions). So you should:

I see, no problem. I can create that Github Action. Do we want to return the PR list or do we want to comment on these PRs with this Github Action as well? It looks like there's [another Github Action](https://github.com/Expensify/Expensify.cash/blob/master/.github/actions/markPullRequestsAsDeployed/action.yml) that takes PR list as an input and adds comment on those PRs as deployed. Do you want me to trigger that Github Action once I get merged PR list in my action?

> 1. Create an action metadata file for a new Github Action similar to [this one](https://github.com/Expensify/Expensify.cash/blob/master/.github/actions/bumpVersion/action.yml)
> 2. Create a Node.js script that _is_ the action. So you shouldn't need to add anything to `GithubUtils`, but instead just have the Node.js script perform the steps you outlined above for the `getReleasePullRequestList` function.
> 
> A few tips:
> 
> * You'll be able to test this action by creating a custom workflow in another repo (or your fork of Expensify.cash), and executing the action as a step in that workflow.
> * You can use the `@actions/core` module to access the inputs defined in the actions metadata file and to emit outputs from the action.
> * You can use `@actions/github` module to get an authenticated `octokit` client.
> * **Important:** Because of the way Github Actions work, we need to pre-compile the JS for our Github Actions (aka the Node.js) script using a software called `ncc`. You can do that by adding your script to the list [here](https://github.com/Expensify/Expensify.cash/blob/master/.github/scripts/buildActions.sh#L13) and running `npm run gh-actions-build`.
>   
>   * _However, if you have a windows computer,_ you'll need to run that compilation in a Linux machine of some sort (probably want to use Ubuntu). We had another contributor create a cloud instance to do that, but I would recommend using Docker to create an ubuntu VM locally on your computer, and run the compilation from in there.
>   * If you have a mac or linux computer, no need to worry about this.

I have a MacBook and I used ncc to build a node js file in the previous task.


> @tugbadogan Does all this make sense? We have a pretty quick timeline we're shooting for on this project so I'd like this done ASAP.

Yes, thanks for the explanation. I'll send the PR soon.

**Comment by roryabraham** [comment]
> Do we want to return the PR list or do we want to comment on these PRs with this Github Action as well?

Just return the list :)

> Do you want me to trigger that Github Action once I get merged PR list in my action

Nope, no need!

**Comment by tugbadogan** [comment]
Hi @roryabraham

I created pull request and tested locally. Now, I will test this Github Action from a sample Github workflow.

I have a question. I realized that octokit returns 30 tags by default and the maximum limit is 100 per page. Do we need to look at further back with pagination or is it enough to look at only the last 100 tags?

**Comment by roryabraham** [comment]
It depends. If `octokit` gives us the 30 _most recent_ tags in the first page it returns, then I think 30 is fine. Otherwise, we just need to make sure we have the most recent tags.

**Comment by tugbadogan** [comment]
Yes, it returns 30 most recent tags in the first page. Then I'm going to remove 100 limit and use default value.
