### ISSUE TITLE
When GSD priority setting is enabled continue to show current chat in LHN while viewing the chat

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/Expensify.cash#1682]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___
Upwork listing: https://www.upwork.com/jobs/~0110ec2c11a21481f0

## Expected Result:
When GSD priority setting is enabled, chat should show in Left Hand Navigation pane while you are viewing it 

## Actual Result:
Chat disappears from Left Hand Navigation pane when you view it

## Action Performed:
1. Open e.cash
2. Ensure you have a couple unread chats in Left Hand Navigation (LHN)
3. Click your user icon - click dropdown to enable GSD Priority Mode
4. Observe unread chats in LHN
5. click one, start typing.
6. Observe the chat disappear from LHN while you're composing/viewing it 

## Platform: 

Desktop App 
 
**Version Number:** Version 1.0.2-12 (v1.0.2-12)

**Notes/Photos/Videos:** 

Viewing Mitch's Settings, notice GSD Priority Mode has been selected and Rafe's unread message in Mitch's Left Hand Navigation pane:
<img width="1197" alt="Screen Shot 2021-03-09 at 8 47 45 AM" src="https://user-images.githubusercontent.com/36425901/110513817-7ed41500-80bb-11eb-8a16-9b3a92f74845.png">

Viewing Mitch's direct message with Rafe, notice its disappearance from Left Hand Navigation:
<img width="1200" alt="Screen Shot 2021-03-09 at 8 50 03 AM" src="https://user-images.githubusercontent.com/36425901/110513833-85fb2300-80bb-11eb-97a2-bd10f9b7dfa6.png">

**Comment by parasharrajat** [comment]
I would like to work on this issue.

## Proposal

We missed the active report check from this condition. 
https://github.com/Expensify/Expensify.cash/blob/fc7e954a21f67d0c4488adc2c6f3c1790d361ec6/src/libs/OptionsListUtils.js#L194-L198

adding following into the if statement will keep the active chat in the sidebar.
``` 
report.reportID !== activeReportID
```
I think we always want to keep the Active chat in the sidebar so we should add this check for all cases.
I will clean the if checks a bit so that it's not looking messy.

**Comment by anthony-hull** [comment]
Wow so fast. Proposal in before it's exported Rajat 👍  🏃 
I would also do the same as above, adding the check for active reports and do some work to make the if statements more readable, it's a pretty simple fix and trying to think of something novel for the sake of it would be pointless. Since I wrote this code I would like to fix the problem for sake of personal pride.

**Comment by MitchExpensify** [comment]
Seeing as you suggested the proposal first, I've sent you the offer in Upwork @parasharrajat. Thanks for also applying @anthony-hull! There will be plenty more issues coming up
