### ISSUE TITLE
[Chat] [IOU] Create Preview Component

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/Expensify.cash#2027]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

This issue builds on top of the existing IOU feature, allows users to create payment requests and group bill splits. The IOU data that you will be displaying is already being [persisted here via Onyx](https://github.com/Expensify/Expensify.cash/blob/d8b9eb500332bf555a4b31f64c5ee26f054c789e/src/libs/actions/Report.js#L250-L251). 

The Preview Component will be displayed within 1:1 and group chats and displays the current state of the IOU between the users. Only the most recent IOU request Action will be displayed as the preview Component. All older actions will simply render the action as a quote message.

**Mobile & mobile web**
<img width="806" alt="DM IOU Preview Request Money Mobile" src="https://user-images.githubusercontent.com/10736861/112036931-195f3a00-8b39-11eb-8324-65c5dd468e32.png">
<img width="806" alt="DM IOU Preview Request Money Mobile" src="https://user-images.githubusercontent.com/10736861/112036942-1cf2c100-8b39-11eb-8659-c2729331e9f5.png">

**Web & Desktop**
![DM IOU Preview Request Money Desktop](https://user-images.githubusercontent.com/10736861/112036846-03ea1000-8b39-11eb-93f0-fee278c924d8.png)
![DM IOU Preview Request Money Desktop (1)](https://user-images.githubusercontent.com/10736861/112036864-06e50080-8b39-11eb-8017-d0891c07e662.png)

**After report is paid**
![Chat (8)](https://user-images.githubusercontent.com/10736861/112201837-94435600-8c08-11eb-9647-017f715933a4.png)

#### Creating an IOU

Creating an IOU transaction will open an IOU report. Multiple IOU transactions are associated with a single report.

The full IOU Modal flow is not yet complete. To get an idea of what the flow will look like, you can  launch the IOUModal by temporarily modifying the routes in CreateMenu. Launch the request money flow with Navigation.navigate(ROUTES.IOU_REQUEST) and the bill split flow with Navigation.navigate(ROUTES.IOU_BILL). You could also navigate to `Expensify.cash/iou/split` or `Expensify.cash/iou/request`

For now, you can create, pay and decline IOUs with the following API requests (collect your authToken from web cookies):

**CreateIOUReport**
```
curl --request POST \
  --url 'https://expensify.cash/api?command=CreateIOUTransaction' \
  --header 'Content-Type: multipart/form-data; boundary=---011000010111000001101001' \
  --cookie 'email=admin%2540verified.com; accountID=262; authToken=B2C581...DAE9A' \
  --form debtorEmail=jules+2@expensify.com \
  --form currency=USD \
  --form 'comment=Ice cream' \
  --form amount=299
```

**Pay IOU**
```
curl --request POST \
  --url 'https://expensify.cash/api?command=PayIOU' \
  --header 'Content-Type: multipart/form-data; boundary=---011000010111000001101001' \
  --cookie 'email=admin%2540verified.com; accountID=262; authToken=B2C581...DAE9A' \
  --form reportID=778 \
  --form paymentMethodType=Venmo
```

**Decline IOU**
```
curl --request POST \
  --url 'https://expensify-jules.ngrok.io/api?command=RejectTransaction' \
  --header 'Content-Type: multipart/form-data; boundary=---011000010111000001101001' \
  --cookie 'email=admin%2540verified.com; accountID=262; authToken=B2C581...DAE9A' \
  --form reportID=776 \
  --form transactionID=4294967349 \
  --form 'comment='\''I dispute this!'\'''
```

### Deliverables
1. The `ReportActionItemIOUPreview` Component should be created which renders the IOU preview depending on the latest IOU data available within Onyx.
    1. Within [Report.getSimplifiedIOUReport](https://github.com/Expensify/Expensify.cash/blob/4bf49a6574cf8f8f838d235a8c9f9a214ae4598a/src/libs/actions/Report.js#L170-L186), we should add extra fields to the simplified object: `chatReportId` so that we can find the IOU report from the chat report ID, `state`, and `status` (used to determine state of the IOU report)
    2. `ReportActionItemIOUPreview` should take `chatReportID`, `action`, and `isMostRecent` as props
    3.  Within the component, we should retrieve the IOU data for the current `chatReportID` via the `reportIOUs_` Onyx key.
2. This Component will be rendered within a chat in place of ReportActionItemMessage each time the action type is equal to `IOUACTION`, here: [ReportActionItemSingle](https://github.com/Expensify/Expensify.cash/blob/2ddccfed128c3a8c21a9219947a9538793499d03/src/pages/home/report/ReportActionItemSingle.js#L40) or [ReportActionItemGrouped](https://github.com/Expensify/Expensify.cash/blob/2ddccfed128c3a8c21a9219947a9538793499d03/src/pages/home/report/ReportActionItemGrouped.js#L16).
3. The Component should consist of two parts, broken down into separate components:
    1. The Quote section **(A):** Displaying the action title in the style of a quote message, as well as a 'View details' link which has no function for the moment. This section will always be displayed.
    2. The IOU Preview UI **(B):** Displaying the IOU amount, currency, participants, and a button or message 'Tom owes Shawn' depending on who owes who. This section will only be displayed in 1:1 chats, if it is the **most recent action** for the associated IOU. 
    1. If the outstanding report `amount` is NOT 0, then we should display the Pay button|Tom owes Shawn UI.
    2. If the amount is 0, and the IOReport `state` == 2, and `status` == 3, then the report has been settled and we should display the Tom paid Shawn UI
    3. Else, if the IOReport `state` == 1, and `status` == 1, then the transaction was cancelled and we should not display section **B**
![Screenshot 2021-03-23 at 15 23 09](https://user-images.githubusercontent.com/10736861/112171426-b4185100-8beb-11eb-9b48-19288d5bfae7.png)
4. If the IOU report is within a group chat, the preview component should not be rendered as the actionType is currently 'TEXT'. If this changes while the work is in progress we will let you know!
5. Currently, currency will be in symbol form ('GBP', 'USD'), for now this is fine but we may find a solution to this while the PR is still in progress.

**Expensify/Expensify Issue URL:** https://github.com/Expensify/Expensify/issues/158104
**Upwork URL:** https://www.upwork.com/jobs/~0139b48473bd72cabb

**Comment by rameshhpathak** [comment]
Hi, here is my take.

I’ll create `ReportActionItemIOUPreview `component which will be used to render the IOU preview from the data available within Onyx 

I will add extra fields (`state`, `status`, and `chatReportId`) 

The newly created ReportActionItemIOUPreview component will take `chatReportID`, `action`, and `isMostRecent `as props 


I will then use `ONYXKEYS.COLLECTION.REPORT_IOUS}${iouReportID}` key within Onyx to get the IOU data for the current `chatReportID`

Render the `ReportActionItemIOUPreview `component instead of `ReportActionItemMessage `within the `ReportActionItemSingle `and `ReportActionItemGrouped`, when the type of action given to them (ReportActionItemSingle or ReportActionItemGrouped) is equal to IOUAction. 

Finally, on the component rendering part, we will need to have two different parts: 

1. Quote Section: For the quote section, I will create a `ReportActionItemQuote `component which displays the action title in the style of a quote message. I will always display this component. 

2. IOU Preview UI section: This section will only be displayed if it is the most recent action for the associated IOU. So, I will use the `isMostRecent` prop above to determine whether to render it. It will display the `IOU amount`, `currency`, `participants`, a `button/message` according to the logic below.

There are a few additional rendering logic needed to configure the component: 

1. When `outstanding report amount !== 0`, we should display the Pay button, and display text saying Person A owes Person B based on the IOUReport 
2. When the amount is 0, and the` IOUReport state == 2`, and `status == 3`, I can assume that the report has been settled so, will just display “Person A paid Person B”
3. Finally, if the `IOReport state ==1`, and` status ==1`, I can assume the transaction was cancelled, so will not display section B. 
4. For the group chat, I will not render the preview component as requested!

### Question
1. I don’t see the Reject button the PreviewUI logic? Should there be one just below the Pay button when report `amount !==0` and we display the Pay Button?

**Comment by Julesssss** [comment]
> I don’t see the Reject button the PreviewUI logic? Should there be one just below the Pay button when report amount !==0 and we display the Pay Button?

Good point. That is out of scope of this issue but to give you an idea of how it will work eventually, when the user taps 'pay' or 'view details' a Modal will be displayed on top of the current page, listing all transactions and allowing the user to pay or decline. So no need to worry about that for now.

There's one other detail I missed in the description: In order to determine who owes who, you can use the `managerEmail` field within the IOUReport data. The manager is the person who currently **owes** money. This is already available to you in the Onyx data. A final point is that you can switch the 'person who owes' by creating another transaction with a larger amount from the other user. This will swap the manager field.

**Comment by rameshhpathak** [comment]
Ah, I got it! 

So, I revise my proposal to use managerEmail within the IOUReportData to determine who owes who. I’ll just use that, and fill it as:

name corresponding to {managerEmail} owes the name not corresponding to {managerEmail}

**Comment by tugbadogan** [comment]
Hi @trjExpensify,

I would like to work on this issue. Here is my proposal:

> 1. The `ReportActionItemIOUPreview` Component should be created which renders the IOU preview depending on the latest IOU data available within Onyx.

I will create `ReportActionItemIOUPreview` component in here:
https://github.com/Expensify/Expensify.cash/tree/master/src/components

>    1. Within [Report.getSimplifiedIOUReport](https://github.com/Expensify/Expensify.cash/blob/4bf49a6574cf8f8f838d235a8c9f9a214ae4598a/src/libs/actions/Report.js#L170-L186), we should add extra fields to the simplified object: `chatReportId` so that we can find the IOU report from the chat report ID, `state`, and `status` (used to determine state of the IOU report)

I will add `chatReportId`,  `state`, and `status` fields to object returned by `getSimplifiedIOUReport()` function in `Report.js`. So these fields will be stores in Onyx.

>    2. `ReportActionItemIOUPreview` should take `chatReportID`, `action`, and `isMostRecent` as props

I will add `chatReportID`, `action`, and `isMostRecent` as props to new UI component `ReportActionItemIOUPreview`.

>    3. Within the component, we should retrieve the IOU data for the current `chatReportID` via the `reportIOUs_` Onyx key.

I will load IOU data from Onyx when this component is mounted.

> 2. This Component will be rendered within a chat in place of ReportActionItemMessage each time the action type is equal to `IOUACTION`, here: [ReportActionItemSingle](https://github.com/Expensify/Expensify.cash/blob/2ddccfed128c3a8c21a9219947a9538793499d03/src/pages/home/report/ReportActionItemSingle.js#L40) or [ReportActionItemGrouped](https://github.com/Expensify/Expensify.cash/blob/2ddccfed128c3a8c21a9219947a9538793499d03/src/pages/home/report/ReportActionItemGrouped.js#L16).

I will use new component if action is equal to `IOUACTION`.

> 3. The Component should consist of two parts, broken down into separate components:
>    1. The Quote section **(A):** Displaying the action title in the style of a quote message, as well as a 'View details' link which has no function for the moment. This section will always be displayed.
>    2. The IOU Preview UI **(B):** Displaying the IOU amount, currency, participants, and a button or message 'Tom owes Shawn' depending on who owes who. This section will only be displayed in 1:1 chats, if it is the **most recent action** for the associated IOU.

I will create 2 separate component for `Quote` and `IOU Preview` UI. I will display `Quote` component all the time. `IOU Preview` part will be displayed on some conditions specified below.

>    3. If the outstanding report `amount` is NOT 0, then we should display the Pay button|Tom owes Shawn UI.

I will display `IOU Preview` UI with `Tom owes Shawn` message if amount is not 0. If the viewer user is the person who owes money, I will add `Pay` button if `isMostRecent` prop is set.

>    4. If the amount is 0, and the IOReport `state` == 2, and `status` == 3, then the report has been settled and we should display the Tom paid Shawn UI

If amount is 0, `state` == 2, `status` == 3, and `isMostRecent` prop is set,  I will display `IOU Preview` UI with `Tom paid Shawn` message. I have a question here. In mockup screenshots paid amount is displayed here ($20). How are we going to get this value since amount is 0 here?

>    5. Else, if the IOReport `state` == 1, and `status` == 1, then the transaction was cancelled and we should not display section **B**]

If amount is 0, `state` == 1, and `status` == 1, then I will display just  `Quote` UI.

> 4. If the IOU report is within a group chat, the preview component should not be rendered as the actionType is currently 'TEXT'. If this changes while the work is in progress we will let you know!

Since we're going to check if `action` type `IOUACTION`, new component won't be used in group chats for now.

I tried to call API via curl but received following message. Should I use expensify.com instead of expensify.cash?

```
<!doctype html><html lang="en"><head><meta charset="utf-8"/><title>Expensify.cash</title><meta name="description" content="Chat and payments are now the same thing. Launching Summer 2021, join the waitlist to be first in line!"><meta property="twitter:card" content="summary"><meta property="twitter:site" content="@expensify"><meta property="og:type" content="website"><meta property="og:site_name" content="Expensify.cash"><meta property="og:url" content="https://expensify.cash"><meta property="og:title" content="Expensify.cash - Chat with friends to send and receive money"><meta property="og:description" content="Chat and payments are now the same thing. Launching Summer 2021, join the waitlist to be first in line!"><meta property="og:image" content="https://expensify.cash/og-preview-image.png"><link rel="stylesheet" href="/css/fonts.css"/><link rel="stylesheet" href="/css/pdf.css"/><style>html,
        body,
        #root,
        #root > div,
        #root > div > div {
            height: 100% !important;
        }
        #drag-area {
            -webkit-app-region: drag;
        }</style><meta name="viewport" content="width=device-width,user-scalable=no,initial-scale=1"><link rel="shortcut icon" id="favicon" href="/favicon.png"></head><body><div style="position: absolute; top: 0; left: 0; right: 0; height: 30px;" id="drag-area"></div><div id="root"></div><script src="/app-365f524e1fdb4b4065a9.bundle.js"></script></body></html>%  
```

**Comment by Julesssss** [comment]
> In mockup screenshots paid amount is displayed here ($20). How are we going to get this value since amount is 0 here?

Ah good point. As we are already storing the transaction data in Onyx, I think we can pass transactions (or maybe just the most recent transaction) as a prop to the PreviewComponent.

Then, we know the IOU was settled, so we should be able to take the most recent transaction and work out who paid who last... Do you think that would work?

> I tried to call API via curl but received following message. Should I use expensify.com instead of expensify.cash?

Whoops, yeah that should work. Let me know if you have any issues here.

**Comment by trjExpensify** [comment]
Awesome, thanks guys! I've sent the offer to you @tugbadogan, as @rameshhpathak I can see that you're working on the currency modal for this project already - which is super valuable and important to complete in tandem with this issue.

**Comment by tugbadogan** [comment]
> Whoops, yeah that should work. Let me know if you have any issues here.

I managed to create IOUReport with API call. I found that created IOU report is stored in Onyx with `reportIOUs_<IOUReportID> `key, do you want me to change it to store as `reportIOUs_<ChatReportID`> or do we need to keep it as is, add `chatReportID` to stored object and search all `reportIOUs_` and filter by `chatReportID` from Onyx value?
```
{"accountID":9784057,"authToken":"...","email":"tugbadogan92@gmail.com","reportID":71560833,"transactionID":"52448701804707841","httpCode":200,"jsonCode":200,"requestID":"090633b53d000007227a9a3000000001"}%  
```

**Comment by tugbadogan** [comment]
Thanks for the offer @trjExpensify, I started working on this issue

**Comment by Julesssss** [comment]
> do you want me to change it to store as reportIOUs_<ChatReportID> or do we need to keep it as is, add chatReportID to stored object and search all reportIOUs_ and filter by chatReportID from Onyx value?

The second method. We'll need to keep using <IOUReportID> for the `GetIOUReport` key as we will depend on this elsewhere.

**Comment by tugbadogan** [comment]
Hi, I have some questions.

1. Do `IOUReportId` and `chatReportID` have 1:1 relationship, can there be only one `IOUReportID` for each `chatReportID`? I'm planning to add `IOUReportID` to report_* object in Onyx. Does that sound good?
2. API doesn't return `state` and `status` when IOU is created. Am I going to use some default values in the beginning?
3. I created IOU Report but from transactions object it is not clear if it is paid or not and what is the outstanding amount.
<img width="752" alt="Screenshot 2021-03-25 at 21 04 58" src="https://user-images.githubusercontent.com/3853003/112543554-d3f77280-8dad-11eb-9bd1-cb8afb95da85.png">

I'm still not clear how to check if amount is 0 or not as specified in the issue.

**Comment by Julesssss** [comment]
Hi @tugbadogan, 

We've just merged some changes to the stored report data which should simplify the following problems, I would suggest you rebase to master to take advantage of this.

> 1. Do IOUReportId and chatReportID have 1:1 relationship, can there be only one IOUReportID for each chatReportID? I'm planning to add IOUReportID to report_* object in Onyx. Does that sound good?

Not quite. Once an IOUReport is settled it will not be reopened for further transactions. In this case we'll create a new IOUReport. So a single ChatReport could have many IOUReports -- but only one will be 'active' at any time. For the front-end UI though, we can link a report to a specific chatReportID.

Good news, we've just made the [change that you're suggesting](https://github.com/Expensify/Expensify.cash/pull/2086/files#diff-8afe5b71ee0436c21364148c86dadd640f2bff3e3d916addbb1f1f6f7e5b6a43R307). You should now see a `iouReportID` field for each report.

> 2. API doesn't return state and status when IOU is created. Am I going to use some default values in the beginning?

I'm not 100% sure on the issue here... is this a problem for the Preview Component, or just with creating the reports for testing?

BTW, There is an additional API we are using to get the full IOU data (see bottom of this message). 

> 3. I created IOU Report but from transactions object it is not clear if it is paid or not and what is the outstanding amount.

You can now [use cachedTotal](https://github.com/Expensify/Expensify.cash/pull/2086/files#diff-8afe5b71ee0436c21364148c86dadd640f2bff3e3d916addbb1f1f6f7e5b6a43R189) for the outstanding amount and here isthe logic for whether the report is paid:
```
cachedTotal != 0 --> report is active, someone owes money
cachedTotal == 0 && status == 3 && stateNum == 2 --> report has been paid
```

With the new changes this should be made simpler for you. You should be able to [use cachedTotal now](https://github.com/Expensify/Expensify.cash/pull/2086/files#diff-8afe5b71ee0436c21364148c86dadd640f2bff3e3d916addbb1f1f6f7e5b6a43R187-R192). 

____________
**'Get full IOU report' API request**
```
curl --request POST \
  --url 'https://expensify.com/api?command=Get' \
  --header 'Content-Type: multipart/form-data; boundary=---011000010111000001101001' \
  --cookie 'email=jules%252B4%2540expensify.com; accountID=308; authToken=A823E455...261A0266' \
  --form returnValueList=reportStuff \
  --form reportIDList=785 \
  --form shouldLoadOptionalKeys=true \
  --form includePinnedReports=true
```

**Comment by tugbadogan** [comment]
@Julesssss thank you for the reply. I rebased my branch on master and I have all the fields for now. 👍
I have another question. I'm planning to use `RenderHTML` component to render quoted message and `View Details` link. Is there a better solution for this because API returns raw text for IOU Actions?

**Comment by iwiznia** [comment]
Can you please link to your draft PR once you have it @tugbadogan?

**Comment by tugbadogan** [comment]
@iwiznia I linked my draft PR here.

**Comment by Julesssss** [comment]
Thanks! 

> Is there a better solution for this because API returns raw text for IOU Actions?

I guess the alternative be to create a Quote component ` | ` (from HTML) and then build the ViewDetails as a regular Text Component? Perhaps this would be preferred, but I think using RenderHTML seems fine for now.
