### ISSUE TITLE
[Chat] Fix backspace to return to previous chat

### ISSUE THREAD

**Issue by kadiealexander** [Expensify/Expensify.cash#2028]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

The behaviour of the back button in a web/mobile browser needs to be refined.

## Expected Result/Deliverable:
You should shift back to the previous chat.

## Actual Result:
In desktop web: it goes to https://expensify.cash/r/ and content stays the same
In android web: it goes out of the app, back to the previous page you had loaded

## Action Performed:
Head to expensify.cash
Open a chat with another user
Switch to another chat
Press the browser's back button

## Workaround:
Click on the previous chat directly.

## Platform:
Where is this issue occurring?

- [x] Web
- [x] Mobile Web
- [ ] iOS
- [ ] Android
- [ ] Desktop App

**Expensify/Expensify Issue URL:** https://github.com/Expensify/Expensify/issues/157550

**Comment by kadiealexander** [comment]
Upwork posting: https://www.upwork.com/jobs/~014dab1ed80ed6c3a2

**Comment by mikeattara** [comment]
Hello @kadiealexander,

I would love to work on this issue, and putting together a proposal.

**Comment by SameeraMadushan** [comment]
Hi @kadiealexander 

I would like to participate in this issue.

### Problem

- Here we have navigation for reports as `r/:reportID`
- So, when we navigate between reports on the web, It only changes the parameter of the URL. It does not change the screen.
- https://github.com/Expensify/Expensify.cash/blob/9b282f10de193d9a4115bc30f51e0dfdb4133050/src/libs/Navigation/linkingConfig.js#L5-L14
- In `react-navigation` it does not push changes between the same screen parameter to navigation history.
- Eg: `/r/123456` to `/r/01010101`

### Solution

- To solve this I will add report navigation to the browser history
- Inside `sidebarLinks.js` `onSelectRow` I will do the following,
```
onSelectRow={(option) => {
    if (getPlatform() === 'web') {
        window.history.pushState({}, '', option.reportID);
    }
    Navigation.navigate(ROUTES.getReportRoute(option.reportID));
    this.props.onLinkClick();
}}
```
- Then on the web back navigation will work
- Also we can move this check to `Navigation.js`. Then it will be available everywhere.

Thanks.

**Comment by mikeattara** [comment]
It's important to use links as the primary way of navigation instead of navigation actions such as `navigation.navigate`. It'll ensure that links are properly usable on web. [reference](https://reactnavigation.org/docs/web-support/)

__My proposal__
- Create a custom link which let us navigate to a screen using a path instead of a screen name based on the [linking options](https://github.com/Expensify/Expensify.cash/blob/9b282f10de193d9a4115bc30f51e0dfdb4133050/src/libs/Navigation/linkingConfig.js).
- The implementation will be similar to  [this](https://reactnavigation.org/docs/use-link-props)

Let me know what you think, thanks in anticipation.

**Comment by marcaaron** [comment]
@kadiealexander This issue needs to be updated since the `r/undefined` issue no longer exists. The issue affecting navigation history is still occurring however. It doesn't matter what web platform we are on the kinds of weird browser button behavior we see are the same.

>It's important to use links as the primary way of navigation instead of navigation actions such as navigation.navigate

Thanks @mikeattara, why is this important exactly?

>In react-navigation it does not push changes between the same screen parameter to navigation history when we use navigation.navigate()

@SameeraMadushan It does seem to work _sometimes_. So could there be a bug somewhere? The solution provided will work for reports so I'm not sure this workaround is what we are looking for. Ideally, we can get to the bottom of why the history is working inconsistently.

**Comment by SameeraMadushan** [comment]
@marcaaron It's not a bug, It's the default behavior of `navigation.navigate`

> navigation.navigate('RouteName') pushes a new route to the stack navigator if it's not already in the stack, otherwise, it jumps to that screen. 

check this on: [https://reactnavigation.org/docs/navigating/#summary
](https://reactnavigation.org/docs/navigating/#summary
)
To show reports we have only one screen. so `navigation.navigate` won't push a new route to the stack and history won't get created.

If we can use `navigation.push('RouteName') ` instead `.navigate` this issue won't be there. Because,

> We can call navigation.push('RouteName') as many times as we like and it will continue pushing routes.

But in the implementation `getActionFromState` doesn't provide `push` method. Do you have any comments on that?

**Comment by marcaaron** [comment]
Ok, allow me to clear something up in case it isn't already known

- We do not use the default implementation of `navigation.navigate()` I'm realizing now that this is probably confusing if one is reading the docs so apologies for that. Our version of `navigation.navigate()` is currently doing this.
https://github.com/Expensify/Expensify.cash/blob/a192dafffe6e60408d37f2e377b6bd6aa053734e/src/libs/Navigation/Navigation.js#L35-L42

[`linkTo`](https://github.com/Expensify/Expensify.cash/blob/a192dafffe6e60408d37f2e377b6bd6aa053734e/src/libs/Navigation/linkTo.js#L7-L37) is an attempt to create a programmatic version of the `<Link />` component (unless we missed something and that assumption is incorrect).

It seems like the code which controls the `window.history` is [here](https://github.com/react-navigation/react-navigation/blob/54739828598d7072c1bf7b369659e3682db3edc5/packages/native/src/useLinking.tsx#L75-L108) in the `react-navigation` package. But it's less clear to me exactly how it's working or why it works inconsistently.

**Comment by marcaaron** [comment]
I think perhaps the solution might lie in these docs -> https://reactnavigation.org/docs/use-link-props
Reading more on this maybe this was not set up correctly.

**Comment by parasharrajat** [comment]
@marcaaron, @SameeraMadushan findings are correct.
```
  if (action !== undefined) {
        root.dispatch(action);
    } else {
        root.reset(state);
    }
 ```
Here the action would always be `navigate` and when the route is the same `navigate` replace the existing state instead of Pushing a new one into History. We can confirm this by logging the state on `History` on Console.

So a solution here could be to Update the LinkTo implementation and adopt the `useLinkProps` implementation which will give us an action option. Now when the route is report route we can pass `StackActions.push(ROUTES.REPORT_WITH_ID, {'reportID': id})` to action which should solve this. 

Check here how Navigate behaves for Stack Navigators https://reactnavigation.org/docs/navigation-prop/#navigate

**Comment by marcaaron** [comment]
I think the solution may be slightly more complex than just using a `PUSH` action (though that does seem like it's an important piece of the puzzle). 

Presently, if we push a new report screen onto the stack this will have weird consequences with the way things are set up now (drawer upon drawer navigator will appear). e.g.
![Screen Shot 2021-03-30 at 8 06 58 AM](https://user-images.githubusercontent.com/32969087/113035503-00551b00-912f-11eb-9874-f4f4faeb68a3.png)

But maybe it would work with things set up a different way e.g. without using the drawer navigator.

**Comment by marcaaron** [comment]
Looked into this some more. It is possible to get around the issue we noticed last time (many drawer navigators stacking) by moving the `ReportScreen` into a `Stack.Navigator`. Then, if we push new `Report` routes the browser history should work more reliably.

However, I also noticed that these Report screens never actually unmount and just stack on top of each other forever. This is the default behavior of `react-navigation` but doesn't make as much sense when we consider the overall design and performance of this app (it's fairly expensive to render the chat screens so pushing an infinite number seems like a dangerous idea). 

But, maybe there's some way to get the screen to unmount if not focused as a workaround here.

Also wondering how a change like this might affect @kidroca's [PR over here](https://github.com/Expensify/Expensify.cash/pull/2221)

**Comment by SameeraMadushan** [comment]
>  I also noticed that these Report screens never actually unmount and just stack on top of each other forever. 

@marcaaron  Pushing new routes in the mobile is fine right? Because when a user opens a report screen and If the user wants to open another report, the user has to go back(when going back will pop the screen) and start the stack from the drawer.

Pushing a new screen won't be a problem on the web, because the dom will just replace the report view with a new report and only the history will be recorded in the browser.

**Comment by kidroca** [comment]
Hmm if the problem is only on mobile this means routing already works correct 

What I expect from the back button when I'm inside a chat is to return me to the LHN though
- I start from the LHN (drawer open)
- I pick a conversation 
- I want to go back - intercept the back button and just open the drawer

Do you also want to be able to return to prior opened chats - the information should be in the navigation state? It will add some complexity but can probably be extracted 

Could you be interested in the simpler approach for the moment though 
- pressing back from a chat expands the LHN 
- pressing back again collapses it and I'm back in the chat?

I don't think any changes will impact my PR a much. My changes are confined in the ReportScreen and it's children, wherever this component is moved it should still work the same.

**Comment by kidroca** [comment]
> If the user wants to open another report, the user has to go back(when going back will pop the screen) and start the stack from the drawer.

As long as there's drawer involved you are still on the Report Screen 
You get the sense that you go back - because you start with the drawer expanded 
But the Report Screen is always mounted the drawer just draws over it
So going back is just opening the drawer over the current screen. Then selecting a chat from the drawer just swaps the screen content. 
With react nav 5 you can add screen definitions to the drawer nav dynamically so that for each chat you'd have a separate screen, selecting a chat would go to that screen and the previous screen should be discarded (though it might be saved by rn nav for back navigation performance) though I don't think it would help the current situation that much

**Comment by SameeraMadushan** [comment]
@kidroca Oh! 👀  That's true.

**Comment by marcaaron** [comment]
>because the dom will just replace the report view with a new report and only the history will be recorded in the browser

@SameeraMadushan I think when we `push()` a screen above another screen both remain mounted. The behavior you are describing does sound like what we'd expect when we use `navigate()` (but I am just guessing based on some quick logging done when the component mounts).

@kidroca That's a great point. And I agree that's 100% what our expectation would be if we were viewing things on mobile. But also makes less sense if we're on desktop where we'd expect to have a normal browser history built up as we navigate around. 

Either way, I think we could in theory switch from a _push_ behavior to a _replace_ behavior depending on if we were on desktop/web or mobile/mWeb. That does sound a little complex, but unsure if `react-navigation` is offering a better way to handle web at the moment.

**Comment by marcaaron** [comment]
Spent some more time looking into this today and came up with a kind of dirty incomplete solution here
https://github.com/Expensify/Expensify.cash/pull/2295/files

Some kind of solution in `react-navigation` would be ideal, but not sure if allowing the option to switch to browser `history.pushState()` type behavior for the `NAVIGATE` action on web with a permanent `drawerType` is a direction they would consider.
