### ISSUE TITLE
Images not uploading when you hit return immediately after pasting

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/Expensify.cash#2063]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

**Expected Result:**
- The Image should upload

**Actual Result:**
- The image doesn't upload and the upload attachment modal closes 

**Action Performed (reproducible steps):**
- Copy an image to clipboard
- Click on compose box in chat with user or test account
- Paste image into compose by by typing `command+v`
- **immediately** tap enter twice or more. 
- Observe image doesn't upload

## Workaround:
Wait a couple of seconds before hitting enter. 

## Platform:
Desktop App

**Version Number:** Desktop v.2-52
**Notes/Photos/Videos:**  https://user-images.githubusercontent.com/22508304/111228887-35476680-85a2-11eb-970c-518ba9fdb640.mp4
**Expensify/Expensify Issue URL:**https://github.com/Expensify/Expensify/issues/157267
Upwork URL: https://www.upwork.com/jobs/~016727690d69f1c182

**Comment by parasharrajat** [comment]
## Proposal
 I investigated this problem thoroughly and I found one more issue linked with this one. Pressing `Enter` key on any modal closes it which is unexpected behavior and not defined anywhere in the code. 

https://user-images.githubusercontent.com/24370807/112470790-16f71d00-8d91-11eb-82e3-e33d14297a6d.mp4

 ## Root Cause
 The `react-native-modal` component creates a backdrop before modal, this backdrop listens for click events. So that we can close the modal on backdrop click. It uses `TouchableWithoutFeedback` which will be rendered on the web with a div with `tabIndex=0`. Browsers are smart, so they switch focus to the elements automatically. When the browser sees a new element with `tabIndex=0`, it moves the focus over it. You can test it after opening the modal and in console log `document.activeElement`. Which would be the backdrop element as this the first element with `tabIndex=0`. So pressing Enter fires a keydown event on the backdrop which as a result OnPress on the backdrop and thus the modal will be closed.
 
 Now in the mentioned issue, we register custom `Enter`key handler here https://github.com/Expensify/Expensify.cash/blob/2b0674b94819926f38e71b4c5c8edf25bebe1ecb/src/components/Modal/BaseModal.js#L38-L41 but they will only fire after the modal is shown. thus backdrop will receive the `Enter` and the modal will be closed.
 
 ## Solution
 1. We move the keyboard events on the `BaseModal` from `'onModalShow` to `onModalWillShow`.
 ```
 onModalWillShow={() => this.subscribeToKeyEvents()}
```
2. We update `onBackdropPress` handler to 
```
  onBackdropPress={(e) => {
                    if (e && e.type === 'keydown' && e.key === 'Enter') {
                        return;
                    }
                    this.props.onClose();
                }}
 ```
 **This will fix the issue.**
 
https://user-images.githubusercontent.com/24370807/112471505-01362780-8d92-11eb-9790-81aa64dfd9ad.mp4

 ### Not Recommended
 3. Now we can also blurr the default Focused elment after modal is shown like,
 ```
 onModalShow={() => {
                    setModalVisibility(true);
                    document.activeElement.blur();
                }}
  ```
  But I **won't suggest it**. It will cause an accessibility issue. Observe the Tab navigation after the modal is opened.  If we blur the default focused element. This behavior won't happen.         

https://user-images.githubusercontent.com/24370807/112470618-deefda00-8d90-11eb-84b8-70034428057c.mp4

**Comment by marcaaron** [comment]
>We move the keyboard events on the BaseModal from 'onModalShow to onModalWillShow.

Thanks Rajat, but why do we need to do this step? Will the solution also work if we do the check in the `onBackdropPress` event?

**Comment by parasharrajat** [comment]
@marcaaron. So the original Issue is that the image should be submitted on immediate enter press. These handlers are the one who submits the image. So they should be ready as early as possible. `onModalShow` fires after the modal are completely visible and the animation has finished. Pressing the enter won't work immediately.  Moving handlers to the `onModalWillShow`, make them available as soon as modal is rendered and modal comes into the visible state before animations and all those things are started.

**Comment by parasharrajat** [comment]
> Will the solution also work if we do the check in the onBackdropPress event
Sorry, but I didn't get this. What check?

**Comment by marcaaron** [comment]
>These handlers are the one who submits the image. So they should be ready as early as possible. onModalShow fires after the modal are completely visible and the animation has finished thus pressing the enter won't work immediately. Moving handlers to the onModalWillShow, make them available as soon as modal is rendered and modal comes into the visible state before animations and all those things are started.

Ok, that doesn't sound like an optimization we need. The modal shows very quickly.

>Sorry, but I didn't get this. What check?
```
if (e && e.type === 'keydown' && e.key === 'Enter') {
```

**Comment by parasharrajat** [comment]
@marcaaron. Yes **solution still works** without moving the keyboard events to `onModalWillShow`. So after pasting the image and pressing enter will not cancel the attachment Modal. But the Image will not be submitted until the modal is shown and then on pressing `Enter` the image will be submitted.

**Comment by kaushiktd** [comment]
Hi,

This is Kaushik here and here is a smiple explanation for this issue,

1.  we will put a timer while process the image to be upload until submit button is not tappable.
