### ISSUE TITLE
[HOLD for payment June 29] Update compose box to send photos and text in one message

### ISSUE THREAD

**Issue by kadiealexander** [Expensify/Expensify.cash#2258]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Expected Result:**
1. When uploading image attachments in Expensify.cash, the [existing attachment preview modal](https://github.com/Expensify/Expensify.cash/blob/ed8b81e78ad3a8c031ad02338e56990cc0c06f3b/src/components/AttachmentModal.js) should appear. Instead of [saying "Upload"](https://github.com/Expensify/Expensify.cash/blob/ed8b81e78ad3a8c031ad02338e56990cc0c06f3b/src/components/AttachmentModal.js#L132), it should now say "Send". 

This should work the same for all three modes of interaction:
    - Manually picking an image using the [AttachmentPicker](https://github.com/Expensify/Expensify.cash/tree/ed8b81e78ad3a8c031ad02338e56990cc0c06f3b/src/components/AttachmentPicker),
    - [Drag-and-dropping a photo into the `ReportActionCompose`](https://github.com/Expensify/Expensify.cash/blob/2336d7bcea21f90044a888c6a804f85f4de2a57c/src/pages/home/report/ReportActionCompose.js#L403-L413),
    - [Pasting a photo into the `ReportActionCompose`](https://github.com/Expensify/Expensify.cash/blob/2336d7bcea21f90044a888c6a804f85f4de2a57c/src/pages/home/report/ReportActionCompose.js#L419) from the platform's native clipboard.

2. After hitting "Send", any draft text in the composition box should be sent, followed by the attached image below the text.

@mallenexpensify @shawnborton if you have nothing else to add here then feel free to apply the `External` label so we can get this on Upwork.

**Actual Result:**
- Image uploads and text in compose box persists. 

## Action Performed:

**Web/Desktop**
- Type text in compose box
- Drag/drop image to compose box to upload 
- Click 'Upload`

**Mobile web/app**
- Type text in compose box
- Tap attachment/paperclip icon
- Tap `Photo Library` or `Choose from Gallery`
- Select photo and tap `Choose` or `Upload` to upload

## Platform:
Where is this issue occurring?

- [x] Web 
- [x]  iOS
- [x]  Android
- [x]  Desktop App
- [x]  Mobile Web

**Version Number:**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:** https://github.com/Expensify/Expensify/issues/156214
**Platform - version:**  All

**Notes/Photos/Videos:** 
Big ol' thread in Slack - [link](https://expensify.slack.com/archives/C011W8BJ9L6/p1611454781167100)
iOS/Messenger is what we're wanting to mimic 
![IMG_5636](https://user-images.githubusercontent.com/22508304/109685611-4457fe80-7b36-11eb-92f6-6e899a3f6ffc.PNG)

![IMG_5637](https://user-images.githubusercontent.com/22508304/109685636-4c17a300-7b36-11eb-9564-f71a1b218f55.PNG)

**Slack does a good job of handling this but they put they post the text above the image.** 
![image](https://user-images.githubusercontent.com/22508304/109685501-2b4f4d80-7b36-11eb-9f31-0b16e79dddbd.png)

**Comment by kadiealexander** [comment]
Upwork post: https://www.upwork.com/jobs/~01f6625d382eb3f5db

**Comment by johndev0711** [comment]
Hello, @kadiealexander. How are you?
I have a good solution about this issue which can solve simply and perfectly. I've ever implemented it on past projects before.
Likewise, I'd love to build a customized component for this feature.
The solution is as follows:
1. Create a composed box which contain drop box and text box.(text box is exist currently).
2. The drop box is displayed when there is any attachment the user want. And the user select the file, it places on the drop box. If there isn't any attachment, the drop box would be hidden.
3. When the user clicks the send button, the data of the composed box will be sent together to the target.

What do you think?
Looking forward to hearing from you soon.

**Comment by JmillsExpensify** [comment]
Hi @johndev0711 apologies for the delay on this one! We're going to take this issue back into an internal planning stage so that we can get more crisp on details. We'll be sure to update this issue in the near future with crisp details on next steps. Thank you!

**Comment by johndev0711** [comment]
Thanks for your info.

**Comment by roryabraham** [comment]
@kadiealexander I see that the [old Upwork listing for this issue](https://www.upwork.com/jobs/~01f6625d382eb3f5db) has been closed. Can you create a new one please so we can push this issue along? As soon as you have the new Upwork posting, please:

1. Update the E/E tracking issue
1. Update the OP of this issue with the new Upwork posting
1. Take this issue off hold

Then we can start taking contributor proposals for this!

**Comment by mallenexpensify** [comment]
I'm going to assign the External label because a) it hasn't been yet and b) because Rory updated the OP so all the details are there for the post.

**Comment by mallenexpensify** [comment]
D'oh, it looks like it stayed assigned to you @kadiealexander cuz you were already assigned (I think).  ¯\_(ツ)_/¯

**Comment by kadiealexander** [comment]
Latest UpWork post: https://www.upwork.com/jobs/~0102615128016a8557

@johndev0711 would you like to keep your proposal in the running here? If you're still interested, could you please have a read of the updated issue and let me know if you think your solution will still apply here?

**Comment by kadiealexander** [comment]
Previous upwork post was removed, here's the new one: https://www.upwork.com/jobs/~017535f570c71c714a

**Comment by Christinadobrzyn** [comment]
Reached out in Upwork to some contractors we've used in the past to see if they are interested in this project.

**Comment by parasharrajat** [comment]
I have a question about 

> If the attachment staging area is not empty and/or there is a draft message in the main ReportActionCompose text input, then after switching to a different report and back, or even after closing the app and reopening it, the draft state of the message and the attachments in the staging area should be preserved.

How are we planning to save the images offline? On slack, it uploads all the images while a user is selecting them. Thus next time we see the draft, it just usages the URLs for that purpose. we can't use Onyx for Web. The web has limited storage of 5Mb which will be overflown by these images.

**Comment by kidroca** [comment]
> How are we planning to save the images offline? On slack, it uploads all the images while a user is selecting them. Thus next time we see the draft, it just usages the URLs for that purpose. we can't use Onyx for Web. The web has limited storage of 5Mb which will be overflown by these images.

You can't use Onyx because Onyx does not have a way to deal with files ATM 
Even if local storage had tons of space it would be a bad idea to convert a file to base64 string and save it there - local storage / AsyncStorage deals only with strings

Native devices (mobile) have dedicated directories for (documents/cache) that you can leverage to temporary store the file until it's uploaded 
Browsers have "cache API" that you can use to manually put stuff including files and has a lot more storage space per domain, browsers support `IndexedDb` as well https://caniuse.com/indexeddb, this technology can be used to cache files: https://hacks.mozilla.org/2012/02/storing-images-and-files-in-indexeddb/

The above is probably already implemented by some library 

What slack does 
- when you have internet access
   - when you select an attachment
   - it starts uploading to slack storage bucket right away 
   - if the image is uploaded by the time you press send it sent right away
   - if it's not you'll see a spinner on it, similar to how it works right now in E.cash
   - if you decide to cancel and not send the message - nothing happens. A service is probably clearing the server bucket from images that aren't posted, or the image is cleared when you press cancel 
- when you don't have internet access
  - when you select an attachment 
  - it's show a spinner on it
  - if you press send - it goes in the chat with a spinner 
  - in a bit you see an error under it - "Couldn't send. Tap to try again" 
  - at this point I think they've saved a copy in cache/documents
  - if you regain internet and type more messages 
  - then retry the message with attachment that failed - it will move after them, becoming the most recent message

**Comment by kidroca** [comment]
@kadiealexander @Christinadobrzyn 
This ticket is listed as a $250 job on Upwork. IMO this is too little for the requirements listed in the description
The Offline handling should probably be a separate task on it's own

**Comment by quinthar** [comment]
I sorta wish we just did the original proposal: send the image and text all
at once, and be done with it.  This feels like it's massively scope-creeped.

**Comment by parasharrajat** [comment]
@kidroca thanks for your input. I had my plans for using IndexedDB. but I want to know what is the team's original plan for offline caching. I agree this little more involved than a normal task.

**Comment by kidroca** [comment]
> > Even if local storage had tons of space it would be a bad idea to convert a file to base64 string and save it there - local storage / AsyncStorage deals only with strings  

> And Base64 is a string after all so it can be saved on Local storage/async storage.

I meant that because AsyncStorage deals only with strings you'd have to use a base64 of the file to save it to AsyncStorage - that's a big NO.
- Big strings moving through the native bridge
- Converting a file to base64 - requires reading the file, then converting that to a string - intenisve. Having a reference to a file does not require you to read it - it's read only when it has to be read - displayed or uploaded - and not when passed around
- Using strings when you can reference files
- Passing string parameters - JS strings are immutable, strings are copied not passed by reference. Passing 2-3MB or even more per single string is not good

> Cache API is not a persistent storage solution so we had to go with Indexed DB.

I thought you needed something until the user is back online, and not to persist files indefinitely 
I think you might be reinventing the wheel here, why not research for something existing first ?

**Comment by parasharrajat** [comment]
Thanks for the clarification. It's more than what I asked and probably not what I asked. Cache storage seems promising. All I am saying is that the main issue description lacks information about storage strategy.

**Comment by Christinadobrzyn** [comment]
Should we go back to this proposal? Upwork post: https://www.upwork.com/jobs/~01f6625d382eb3f5db

**Comment by roryabraham** [comment]
@Christinadobrzyn I'm not seeing any details related to this issue in that Upwork post.

> I sorta wish we just did the original proposal: send the image and text all
at once, and be done with it. This feels like it's massively scope-creeped.

It's not really clear to me what you're suggesting – the original proposal in my opinion was a bit half-baked and didn't have a clear answers to a number of questions around how this feature would really work. If we want to reduce the scope of this issue, the following are the items I think we could remove from the scope of this issue and handle in follow-ups:

- **(5)** Tapping on any thumbnail in the attachment staging area should open that attachment in the full-screen modal. This time, the modal button should say "Remove" instead of "Attach". Pressing "Remove" should remove the thumbnail from the attachment staging area. Closing the modal without pressing remove should leave the thumbnail in place. The full-screen modal also should not have an option to download the file in the attachment staging area, because that file will have just been uploaded by the user.
- **(9)** If the attachment staging area is not empty and/or there is a draft message in the main ReportActionCompose text input, then after switching to a different report and back, or even after closing the app and reopening it, the draft state of the message and the attachments in the staging area should be preserved.

I think that all the other pieces are pretty critical to this feature working as it should. We could also make it so that only one image can be attached at a time, but that seems like an artificial limitation that won't actually reduce the scope of work here by a great deal.

Thoughts?

> All I am saying is that the main issue description lacks information about storage strategy.

This is true, and not something we discussed in the original issue before posting this to Upwork. Let's continue to discuss the best plan forward.

#### iOS/Android

> Native devices (mobile) have dedicated directories for (documents/cache) that you can leverage to temporary store the file until it's uploaded

Would we be able to leverage [react-native-fs](https://github.com/itinance/react-native-fs#readme) to achieve this?

#### Web / Desktop

I unfortunately don't have any experience with `IndexedDB` but it seems like a promising solution for web. It looks like [we can use the same for Electron](https://livebook.manning.com/book/electron-in-action/chapter-12/14)

**Comment by roryabraham** [comment]
Curious for input from other Expensifiers here too regarding the `IndexedDB` web API, maybe @AndrewGable, @marcaaron or @cead22?

**Comment by parasharrajat** [comment]
We should not leave the Offline support for this feature. It's better to be planned accordingly and then implemented. We definitely need a way to reference the images for draft messages.

**Comment by cead22** [comment]
I've never used it so I'm not familiar with it

**Comment by marcaaron** [comment]
I think we should just forget about the images in the drafts. It's a nice idea, but if it's significantly easier to save a text draft than an image we should just go with that for now? Seems more important to preserve a draft of text than it is to preserve something queued for upload (that likely already exists on your device). We can always iterate on this later and improve it down the line. Getting the compose box UI updated is already going to be a lift so we should maybe just drop this requirement:

>If the attachment staging area is not empty and/or there is a draft message in the main ReportActionCompose text input, then after switching to a different report and back, or even after closing the app and reopening it, the draft state of the message and the attachments in the staging area should be preserved.

**Comment by Christinadobrzyn** [comment]
Thanks for confirming @marcaaron - in terms of getting this proposal into Upwork, are we going back to the OP minus step 9?

**Comment by roryabraham** [comment]
After some [internal discussion](https://github.com/Expensify/Expensify/issues/156214#issuecomment-859974940), I think we should massively scale back this issue for now, and just do the following:

1. Change `Upload` to `Send` in the upload-attachment modal. This should resolve any concerns that sending the attachment immediately is unexpected behavior.
1. When that button is clicked, send any draft text message first, _then_ upload and sent the attachment. That way, the text you've composed appears above the attachment you're including in the report history.
1. Punt the remaining features (i.e: an "attachment staging area" that can support multiple attachments, saving draft images for later upload, etc...) for later.

We can revisit a more comprehensive overhaul of the image-upload experience in a few months when it fits better with our priorities.

**Comment by parasharrajat** [comment]
Let me be clear here
1. When a user uploads an image, Change the modal title to `send`.
2. If there is was text in the composer send that first and then image.
3. What button? Attachment Modal's button, Composer send button. 

or After the user click confirms on the attachment Modal, Show that image in the composer, and then on click at the `send` button, send the text and image, respectively.

Also, Requesting OP to update the main description. Thanks.

**Comment by roryabraham** [comment]
> When a user uploads an image, Change the modal title to send.

Modal title, and the attachment modal's `Upload` button.

> If there is was text in the composer send that first and then image

yes.

> What button? Attachment Modal's button, Composer send button.

Attachment modal's button.

**Comment by kadiealexander** [comment]
@parasharrajat I have updated the OP to reflect the new task, please let me know if you have any questions about this!

**Comment by kadiealexander** [comment]
@parasharrajat Just wanted to check if you're still interested in this issue?

**Comment by parasharrajat** [comment]
@kadiealexander Sorry, it got slipped out of my mind. I will submit the proposal today and start work asap.

**Comment by parasharrajat** [comment]
### Proposal
1. If we simply want to change the Title of Attachment Modal then we need to change the title here https://github.com/Expensify/Expensify.cash/blob/91a2f1ae9bf72077b41867d64a611eecdaed1b3f/src/components/AttachmentModal.js#L121
To localized send string.
2.  Change the button text as well https://github.com/Expensify/Expensify.cash/blob/91a2f1ae9bf72077b41867d64a611eecdaed1b3f/src/components/AttachmentModal.js#L140.
3. Then we need to modify the onConfrim callback of AttachmentModal so that it submits the text in composer first if any and then images.
it can be simply done by calling the `submitForm` method here  https://github.com/Expensify/Expensify.cash/blob/91a2f1ae9bf72077b41867d64a611eecdaed1b3f/src/pages/home/report/ReportActionCompose.js#L405-L408;
```
 onConfirm={(file) => {
                            this.submitForm();
                            addAction(this.props.reportID, '', file);
                            this.setTextInputShouldClear(false);
   }}
```
`SubmitForm` automatically checks the comment before sending so it will just work fine.

**Comment by roryabraham** [comment]
Nice, proposal looks good to me @parasharrajat 👍

**Comment by parasharrajat** [comment]
Lol, I was just going to ping. Thanks for confirming PR is ready.

**Comment by Jag96** [comment]
Updated title to HOLD for payment

**Comment by parasharrajat** [comment]
@kadiealexander any update here for me. thanks.

**Comment by kadiealexander** [comment]
@parasharrajat sorry about this, the job was moved to our Enterprise login and a bit of weirdness occurred. I've just sent an offer in Upwork, if you could please accept this and I'll issue payment.

**Comment by parasharrajat** [comment]
Done

**Comment by kadiealexander** [comment]
Paid via Upwork.
