### ISSUE TITLE
Discuss: Improvements to Navigation

### ISSUE THREAD

**Issue by marcaaron** [Expensify/Expensify.cash#250]
Currently, we are using React Router together w/ Ion (our prototype global state management solution) to handle site navigation. There are a couple of potential issues with this that I wanted to discuss...

### Avoid Tightly Coupling React Router w/ Ion (or any other global state)

At the moment, we can "redirect" to another screen in the app by setting a key in Ion. This seems convenient, but I wonder if it's actually necessary and can't think of any great reasons why we should do this. If we are sticking with React Router then we already more or less get global app navigation for free (while inside components at least) - see [`withRouter` HOC](https://reactrouter.com/web/api/withRouter). 

While working through some bugs in the codebase I found it very confusing to tell what sorts of things would cause a redirect and we should try to be as predictable as possible when it comes to redirects that are side effects of making API calls etc.

As far as I can tell there is no use case for storing a redirect direction in a persistent way. And in my opinion site redirects should be _instant_ (e.g. `this.props.history.push()` or a `<Link/>`) and not need to touch Ion code at all. 

**Ultimately I think our site navigation strategies need to be:**

1. Well documented
1. Predictable
1. Easy for engineers to follow and implement

If we don't do this then we will likely find ourselves chasing down bugs or introducing hacks to overcome poorly understood redirect logic. Which will translate to a more brittle system that can easily be broken and possibly not caught in regressions tests. Which is obviously bad for the user.

### Using React Navigation

This might require further investigation but I believe by using React Router on native mobile we are losing some of the features of native app navigation. I'm thinking of things like tab navigators, drawers, Android back button, etc. In the prototype, we get around this by using some simple views and animations to create a slide out drawer navigator. Based on [this](https://reactnavigation.org/docs/web-support/) I believe it would be possible to integrate something like `react-navigation` with RN4W (React Native for Web).

Don't hate me. I haven't _quite_ done this research yet to see how feasible it would be to combine React Navigation with RN4W but my rough hypothesis here is... **we should explore using React Navigation because it takes advantage of _existing native app navigation patterns_ and will feel more natural + possibly have better performance than React Router when run on mobile apps - which are arguably the most important platform we have**.

https://reactnavigation.org

**Comment by Julesssss** [comment]
I'd like to reopen this issue for further discussion. 

Until now we haven't really had to worry about navigating between pages, but with the addition of Settings/Profile and the P2P manual payments flows we are starting to implement a navigation hierarchy and I would like to push for us to revisit. I don't see any argument against the mobile benefits here, but to highlight the importance, I don't think we can launch without native-like navigation (native page change animations to represent page hierarchy, Android back button to clear page stack) without this the app feels like a web-app and won't appeal to native mobile users. 

It seems that working out how to manage web is the blocking issue here. Has anyone had any further thoughts regarding react-navigation or alternatives since this was last discussed?

**Comment by Julesssss** [comment]
Hmm, perhaps I should have opened the internal issue instead.
